#config_version=6

mode:
  start_events: ball_started
  code: daily_bugle_mystery.DailyBugleMystery
  priority: 90

event_player:

  # A rollovers
  s_inlane_a_active:
    - daily_bugle_a_hit

  s_inlane_m_r_active:
    - daily_bugle_a_hit

  # B rollovers
  s_inlane_b_active:
    - daily_bugle_b_hit

  s_inlane_m_l_active:
    - daily_bugle_b_hit

  # Successful rooftop traversal
  s_upper_exit_right_opto_active:
    - daily_bugle_rooftop_right_exit

  # VUK collects mystery when ready
  s_vuk_switch_active:
    - daily_bugle_vuk_collect_request

  daily_bugle_widget_update:
    - daily_bugle_widget_remove
    - daily_bugle_widget_readd|10ms

widget_player:
  daily_bugle_widget_remove:
    daily_bugle_ready:
      action: remove

  daily_bugle_widget_readd:
    daily_bugle_ready:
      action: play


variable_player:
  mystery_award_million_points:
    score: 1000000


random_event_player:
  daily_bugle_mystery_ready:
    - daily_bugle_rooftop_right_exit_1
    - daily_bugle_rooftop_right_exit_2

sound_player:
  daily_bugle_a_complete{current_player.daily_bugle_b_hit == 0}:
    hub_create_gem:
      action: play
      bus: effects
  daily_bugle_b_complete{current_player.daily_bugle_a_hit == 0}:
    hub_create_gem:
      action: play
      bus: effects

  ab_rolledover_sfx:
    le_hit:
      action: play
      bus: effects

  daily_bugle_ab_complete:
    sm_i_better_take_some_photos:
      action: play
      bus: voice
  daily_bugle_rooftop_right_exit_1:
    sm_i_hope_mr_jameson_likes:
      action: play
      bus: voice
  daily_bugle_rooftop_right_exit_2:
    sm_i_wonder_what_mr_jameson:
      action: play
      bus: voice
  mystery_award_ball_save:
    sm_a_safety_net:
      action: play
      bus: voice
  mystery_award_start_super_spinner:
    sm_super_spinner:
      action: play
      bus: voice
  mystery_award_advance_bonus_multiplier:
    sm_a_bigger_reward:
      action: play
      bus: voice
  mystery_award_collect_bonus:
    sm_oh_i_love_bonus_points:
      action: play
      bus: voice
  mystery_award_hold_bonus:
    sm_ill_keep_these:
      action: play
      bus: voice
  mystery_award_start_super_pops:
    sm_super_pops:
      action: play
      bus: voice
  mystery_award_million_points:       
    sm_a_million_points:
      action: play
      bus: voice
  mystery_award_villain_start_ready:
    sm_i_wonder_what_mr_jameson:
      action: play
      bus: voice


show_player:

  daily_bugle_a_complete:
    daily_bugle_a_complete_show:
      loops: -1

  daily_bugle_b_complete:
    daily_bugle_b_complete_show:
      loops: -1

  daily_bugle_ab_complete:
    daily_bugle_a_complete_show:
      action: stop
    daily_bugle_b_complete_show:
      action: stop
    daily_bugle_ab_ready_show:
      loops: 3
    daily_bugle_spinner_ready_show:
      loops: -1

  daily_bugle_rooftop_traversal_complete:
    daily_bugle_ab_off_show:
      loops: 0
    daily_bugle_spinner_ready_show:
      action: stop
    daily_bugle_mystery_ready_show:
      loops: -1

  daily_bugle_mystery_collected:
    daily_bugle_mystery_ready_show:
      action: stop
    daily_bugle_mystery_collect_show:
      loops: 4

  daily_bugle_mystery_stop_all:
    daily_bugle_a_complete_show:
      action: stop
    daily_bugle_b_complete_show:
      action: stop
    daily_bugle_ab_ready_show:
      action: stop
    daily_bugle_spinner_ready_show:
      action: stop
    daily_bugle_mystery_ready_show:
      action: stop
    daily_bugle_mystery_collect_show:
      action: stop


shows:

  daily_bugle_a_complete_show:
    - duration: 300ms
      lights:
        l_a_rollover: white
        l_right_a: white
    - duration: 300ms
      lights:
        l_a_rollover: blue
        l_right_a: blue

  daily_bugle_b_complete_show:
    - duration: 300ms
      lights:
        l_b_rollover: white
        l_left_b: white
    - duration: 300ms
      lights:
        l_b_rollover: blue
        l_left_b: blue

  daily_bugle_ab_off_show:
    - duration: 300ms
      lights:
        l_a_rollover: off
        l_right_a: off
        l_b_rollover: off
        l_left_b: off

  daily_bugle_ab_ready_show:
    - duration: 300ms
      lights:
        l_a_rollover: white
        l_right_a: white
        l_b_rollover: white
        l_left_b: white
    - duration: 300ms
      lights:
        l_a_rollover: blue
        l_b_rollover: blue
        l_right_a: blue
        l_left_b: blue

  daily_bugle_spinner_ready_show:
    - duration: 400ms
      lights:
        l_spinner: white
    - duration: 400ms
      lights:
        l_spinner: blue

  daily_bugle_mystery_ready_show:
    - duration: 250ms
      lights:
        l_spinner: green
    - duration: 250ms
      lights:
        l_spinner: off

  daily_bugle_mystery_collect_show:
    - duration: 150ms
      lights:
        gi: white
    - duration: 150ms
      lights:
        gi: blue        
        