#config_version=6

mode:
  start_events: start_mode_super_swami
  stop_events:
    - super_swami_mode_complete
    - super_swami_mode_failed
    - ball_ended
  code: super_swami.SuperSwami
  priority: 300

widget_player:
  mode_super_swami_started:
    super_swami:
      action: play
  super_swami_mode_complete:
    super_swami:
      action: remove
  mode_super_swami_stopping:
    super_swami:
      action: remove

event_player:
  s_saucer_1_active: clear_saucers
  s_saucer_2_active: clear_saucers
  s_saucer_3_active: clear_saucers
  mode_super_swami_stopping:
    - clear_saucers
    - drop_target_bank_dt_bank_left_reset
    - drop_target_bank_dt_bank_right_reset

light_player:
  super_swami_dim_city:
    l_gi_3bank: 404040
    l_gi_5bank_lower: 404040
    l_gi_5bank_upper: 404040
    l_gi_a: 404040
    l_gi_ab: 404040
    l_gi_bright: 404040
    l_gi_left_lower: 404040
    l_gi_left_sling_lower: 404040
    l_gi_left_sling_upper: 404040
    l_gi_left_upper: 404040
    l_gi_left_upper_flipper: 404040
    l_gi_mid_spider: 404040
    l_gi_ramp: 404040
    l_gi_right_lower_triangle: 404040
    l_gi_right_return: 404040
    l_gi_right_sling: 404040
    l_gi_spinner: 404040
    l_gi_top_1: 404040
    l_gi_top_2: 404040
    l_gi_top_3: 404040
    l_gi_top_4: 404040
    l_gi_upflip: 404040
    l_pop_1_1: 404040
    l_pop_1_10: 404040
    l_pop_1_11: 404040
    l_pop_1_12: 404040
    l_pop_1_2: 404040
    l_pop_1_3: 404040
    l_pop_1_4: 404040
    l_pop_1_5: 404040
    l_pop_1_6: 404040
    l_pop_1_7: 404040
    l_pop_1_8: 404040
    l_pop_1_9: 404040
    l_pop_2_1: 404040
    l_pop_2_10: 404040
    l_pop_2_11: 404040
    l_pop_2_12: 404040
    l_pop_2_2: 404040
    l_pop_2_3: 404040
    l_pop_2_4: 404040
    l_pop_2_5: 404040
    l_pop_2_6: 404040
    l_pop_2_7: 404040
    l_pop_2_8: 404040
    l_pop_2_9: 404040
  super_swami_restore_upper_left:
    l_gi_ramp: FFFFFF
    l_gi_top_1: FFFFFF
    l_gi_top_2: FFFFFF
    l_pop_1_1: FFFFFF
    l_pop_1_11: FFFFFF
    l_pop_1_12: FFFFFF
  super_swami_restore_upper_right:
    l_gi_a: FFFFFF
    l_gi_ab: FFFFFF
    l_gi_bright: FFFFFF
    l_gi_mid_spider: FFFFFF
    l_gi_top_3: FFFFFF
    l_gi_top_4: FFFFFF
    l_gi_upflip: FFFFFF
    l_pop_2_1: FFFFFF
    l_pop_2_11: FFFFFF
    l_pop_2_12: FFFFFF
  super_swami_restore_middle_left:
    l_gi_3bank: FFFFFF
    l_gi_left_lower: FFFFFF
    l_gi_left_upper: FFFFFF
    l_gi_left_upper_flipper: FFFFFF
    l_gi_spinner: FFFFFF
    l_pop_1_10: FFFFFF
    l_pop_1_2: FFFFFF
    l_pop_1_3: FFFFFF
    l_pop_1_4: FFFFFF
    l_pop_1_5: FFFFFF
    l_pop_1_6: FFFFFF
    l_pop_1_7: FFFFFF
    l_pop_1_8: FFFFFF
    l_pop_1_9: FFFFFF
  super_swami_restore_middle_right:
    l_gi_5bank_lower: FFFFFF
    l_gi_5bank_upper: FFFFFF
    l_gi_right_lower_triangle: FFFFFF
    l_pop_2_10: FFFFFF
    l_pop_2_2: FFFFFF
    l_pop_2_3: FFFFFF
    l_pop_2_4: FFFFFF
    l_pop_2_5: FFFFFF
    l_pop_2_6: FFFFFF
    l_pop_2_7: FFFFFF
    l_pop_2_8: FFFFFF
    l_pop_2_9: FFFFFF
  super_swami_restore_lower_left:
    l_gi_left_sling_lower: FFFFFF
    l_gi_left_sling_upper: FFFFFF
  super_swami_restore_lower_right:
    l_gi_right_return: FFFFFF
    l_gi_right_sling: FFFFFF
  super_swami_restore_all_lights:
    l_gi_3bank: E0E0E0
    l_gi_5bank_lower: E0E0E0
    l_gi_5bank_upper: E0E0E0
    l_gi_a: E0E0E0
    l_gi_ab: E0E0E0
    l_gi_bright: E0E0E0
    l_gi_left_lower: E0E0E0
    l_gi_left_sling_lower: E0E0E0
    l_gi_left_sling_upper: E0E0E0
    l_gi_left_upper: E0E0E0
    l_gi_left_upper_flipper: E0E0E0
    l_gi_mid_spider: E0E0E0
    l_gi_ramp: E0E0E0
    l_gi_right_lower_triangle: E0E0E0
    l_gi_right_return: E0E0E0
    l_gi_right_sling: E0E0E0
    l_gi_spinner: E0E0E0
    l_gi_top_1: E0E0E0
    l_gi_top_2: E0E0E0
    l_gi_top_3: E0E0E0
    l_gi_top_4: E0E0E0
    l_gi_upflip: E0E0E0
    l_pop_1_1: E0E0E0
    l_pop_1_10: E0E0E0
    l_pop_1_11: E0E0E0
    l_pop_1_12: E0E0E0
    l_pop_1_2: E0E0E0
    l_pop_1_3: E0E0E0
    l_pop_1_4: E0E0E0
    l_pop_1_5: E0E0E0
    l_pop_1_6: E0E0E0
    l_pop_1_7: E0E0E0
    l_pop_1_8: E0E0E0
    l_pop_1_9: E0E0E0
    l_pop_2_1: E0E0E0
    l_pop_2_10: E0E0E0
    l_pop_2_11: E0E0E0
    l_pop_2_12: E0E0E0
    l_pop_2_2: E0E0E0
    l_pop_2_3: E0E0E0
    l_pop_2_4: E0E0E0
    l_pop_2_5: E0E0E0
    l_pop_2_6: E0E0E0
    l_pop_2_7: E0E0E0
    l_pop_2_8: E0E0E0
    l_pop_2_9: E0E0E0
  super_swami_light_vuk:
    l_advance_multiplier: white
    l_mid_multibonus: white
    l_mid_web_target: white
