#config_version=6

mode:
  start_events: ball_started
  priority: 100

variable_player:
  mode_qualify_upper_access_started:
    villain_mode_running:
      action: set
      int: 0
    villain_start_ready:
      action: set
      int: 0

event_player:

  # Any saucer opens upper access if no villain is running/ready
  s_saucer_1_active:
    - rooftop_access_request

  s_saucer_2_active:
    - rooftop_access_request

  s_saucer_3_active:
    - rooftop_access_request

  rooftop_access_request{current_player.villain_mode_running == 0 and current_player.villain_start_ready == 0}:
    - rooftop_access_open

  rooftop_access_open:
    - rooftop_diverter_open
    - rooftop_access_lit

  timer_rooftop_access_timer_complete:
    - rooftop_access_close

  rooftop_access_close:
    - rooftop_diverter_close
    - rooftop_access_unlit

  # VUK reached: close gate, stop access lighting, then kick/hold
  s_vuk_switch_active:
    - rooftop_vuk_entered

#may need to add another condition - if we need another mode to handle it
  rooftop_vuk_entered{current_player.villain_mode_running == 0 and current_player.villain_start_ready == 0}:
    - rooftop_diverter_close
    - rooftop_access_unlit
    - up_kick|1s

  # Ball has actually landed on upper playfield
  s_upper_entrance_opto_active:
    - rooftop_upper_entered

timers:
  rooftop_access_timer:
    start_value: 8
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: restart
        event: rooftop_access_open
      - action: stop
        event: rooftop_vuk_entered
      - action: stop
        event: villain_start_ready

show_player:
  rooftop_access_lit:
    rooftop_access_show:
      loops: -1

  rooftop_access_unlit:
    rooftop_access_show:
      action: stop

  villain_start_ready:
    rooftop_access_show:
      action: stop

shows:

  rooftop_access_show:
    - duration: 200ms
      lights:
        l_1_hole_l: F0F0F0
        l_1_hole_r: F0F0F0
        l_2_hole_l: F0F0F0
        l_2_hole_r: F0F0F0
        l_3_hole_l: F0F0F0
        l_3_hole_r: F0F0F0
    - duration: 800ms
      lights:
        l_1_hole_l: A0A0A0
        l_1_hole_r: A0A0A0
        l_2_hole_l: A0A0A0
        l_2_hole_r: A0A0A0
        l_3_hole_l: A0A0A0
        l_3_hole_r: A0A0A0

