#config_version=6

mode:
  start_events: start_mode_vulture
  stop_events:
    - vulture_mode_complete
    - ball_ended
  code: vulture.Vulture
  priority: 300

multiballs:
  vulture_add_a_ball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 10s
    start_events: start_vulture_add_a_ball

variable_player:
  multiball_vulture_add_a_ball_started:
    multiball_autoplunge_active:
      action: set
      int: 1

  multiball_vulture_add_a_ball_ended:
    multiball_autoplunge_active:
      action: set
      int: 0

  timer_vulture_mode_timer_complete:
    vulture_time_expired:
      action: set
      int: 1

  mode_vulture_started:
    vulture_time_expired:
      action: set
      int: 0


event_player:
  mode_vulture_started:
    - rooftop_diverter_open
    - clear_saucers
    - vulture_show_targets
    
  drop_target_bank_dt_bank_left_down:
    - drop_target_bank_dt_bank_left_reset

  drop_target_bank_dt_bank_right_down:
    - drop_target_bank_dt_bank_right_reset

  s_saucer_1_active:
    - clear_saucers
    
  s_saucer_2_active:
    - clear_saucers
    
  s_saucer_3_active:
    - clear_saucers    

  timer_vulture_mode_timer_complete{current_player.multiball_autoplunge_active == 0}:
    - vulture_mode_complete

  multiball_vulture_add_a_ball_ended{current_player.vulture_time_expired == 1}:
    - vulture_mode_complete

  timer_vulture_idle_timer_complete:
    - vulture_idle_decay

  vulture_mode_complete:
    - reset_villain_locate

  s_upper_entrance_opto_active:
    - vulture_upper_entered
    - vulture_upper_switch_hit

  s_upper_exit_left_opto_active:
    - vulture_upper_exited
    - vulture_upper_switch_hit

  s_upper_exit_right_opto_active:
    - vulture_upper_exited
    - vulture_upper_switch_hit

  s_upper_target_left_active:
    - vulture_upper_switch_hit
    - vulture_left_target_hit

  s_upper_target_center_active:
    - vulture_upper_switch_hit
    - vulture_center_target_hit

  s_upper_target_right_active:
    - vulture_upper_switch_hit
    - vulture_right_target_hit

  s_trispinner_opto_active:
    - vulture_upper_switch_hit
    - vulture_spinner_hit

timers:
  vulture_mode_timer:
    start_value: 40
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: vulture_timer_start
        action: start
      - event: vulture_mode_complete
        action: stop

  vulture_idle_timer:
    start_value: 3
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: vulture_upper_switch_hit
        action: restart
      - event: vulture_restart_idle_timer
        action: restart
      - event: vulture_mode_complete
        action: stop

show_player:

  vulture_show_left_yellow:
    vulture_left_yellow:
      loops: -1

  vulture_show_left_orange:
    vulture_left_yellow:
      action: stop
    vulture_left_orange:
      loops: -1

  vulture_show_left_red:
    vulture_left_yellow:
      action: stop
    vulture_left_orange:
      action: stop
    vulture_left_red:
      loops: -1

  vulture_show_center_yellow:
    vulture_center_yellow:
      loops: -1

  vulture_show_center_orange:
    vulture_center_yellow:
      action: stop
    vulture_center_orange:
      loops: -1

  vulture_show_center_red:
    vulture_center_yellow:
      action: stop
    vulture_center_orange:
      action: stop
    vulture_center_red:
      loops: -1

  vulture_show_right_yellow:
    vulture_right_yellow:
      loops: -1

  vulture_show_right_orange:
    vulture_right_yellow:
      action: stop
    vulture_right_orange:
      loops: -1

  vulture_show_right_red:
    vulture_right_yellow:
      action: stop
    vulture_right_orange:
      action: stop
    vulture_right_red:
      loops: -1

  vulture_two_balls_upper:
    vulture_two_balls_upper_show:
      loops: 1

  vulture_add_a_ball:
    vulture_add_a_ball_show:
      loops: 1

  vulture_mode_complete:
    vulture_left_yellow:
      action: stop
    vulture_left_orange:
      action: stop
    vulture_left_red:
      action: stop
    vulture_center_yellow:
      action: stop
    vulture_center_orange:
      action: stop
    vulture_center_red:
      action: stop
    vulture_right_yellow:
      action: stop
    vulture_right_orange:
      action: stop
    vulture_right_red:
      action: stop

shows:
  vulture_left_yellow:
    - duration: 1s
      lights:
        l_upper_left: D0D020

  vulture_left_orange:
    - duration: 1s
      lights:
        l_upper_left: orange

  vulture_left_red:
    - duration: 1s
      lights:
        l_upper_left: red

  vulture_center_yellow:
    - duration: 1s
      lights:
        l_upper_middle: D0D020

  vulture_center_orange:
    - duration: 1s
      lights:
        l_upper_middle: orange

  vulture_center_red:
    - duration: 1s
      lights:
        l_upper_middle: red

  vulture_right_yellow:
    - duration: 1s
      lights:
        l_upper_right: D0D020

  vulture_right_orange:
    - duration: 1s
      lights:
        l_upper_right: orange

  vulture_right_red:
    - duration: 1s
      lights:
        l_upper_right: red

  vulture_add_a_ball_show:
    - duration: 150ms
      lights:
        gi: white
    - duration: 150ms
      lights:
        gi: yellow

  vulture_two_balls_upper_show:
    - duration: 100ms
      lights:
        gi: red
    - duration: 100ms
      lights:
        gi: yellow