#config_version=6
#base mode config file
mode:
  start_events: ball_started
  priority: 100


event_player:
  mode_base_started:
    - music_start_prowl|1s

  s_plunger_inactive:
    - start_my_default_ball_save


slide_player:
  mode_base_started:
    base:
      action: play
    attract:
      action: remove

timers:
  timer_up_post_hold:
    start_value: 0
    end_value: 6
    tick_interval: 1s
    control_events:
      - action: restart
        event: enable_up_post_event
        
light_player:
  mode_base_started:
    gi:
      color: E0E0E0        
  ramp_raise:
    gi:
      color: F0F000        
  ramp_lower:
    gi:
      color: F00000        
  s_upper_exit_left_opto_active:
    gi:
      color: E0E0E0        
  s_upper_exit_right_opto_active:
    gi:
      color: E0E0E0        
      
sound_player:
  s_web_spinner_active{mode.super_spinner.active == False}:
    rope_1:
      action: play
      bus: effects

  s_outlane_r_active{current_player.ball_save_count == 0}:
    jj_end_of_the_line:
      action: play
      bus: voice

  s_outlane_l_active{current_player.ball_save_count == 0}:
    jj_spiderman_caught:
      action: play
      bus: voice
