#config_version=6
#base mode config file
mode:
  start_events: ball_started
  priority: 100


variable_player:
  secondary_switch_hit:
    score: 500

  pops_hit:
    score: 1100

  drop_hit_no_mode:
    score: 2000


random_event_player:
  play_random_main_song:
    - play_song_1
    - play_song_2
    - play_song_9
    - play_song_16


event_player:
  finish_skillshot:
    - play_random_main_song

  mode_base_started:
    - mode_base_started_delayed|1s

  mode_base_started_delayed:
    - play_song_5

  s_plunger_inactive:
    - start_my_default_ball_save

  s_leaf_next_to_1_active:
    - secondary_switch_hit
  s_right_drops_top_rubber_active:
    - secondary_switch_hit  
  s_above_star_active:
    - secondary_switch_hit
  s_above_spinner_active:
    - secondary_switch_hit
  s_left_drops_top_left_rubber_active:
    - secondary_switch_hit
  s_left_drops_top_right_rubber_active:
    - secondary_switch_hit
  s_mid_right_rubber_active:
    - secondary_switch_hit
  s_left_drops_rubber_active:
    - secondary_switch_hit
  s_right_drops_rubber_active:
    - secondary_switch_hit

  s_pop_right_active:
    - pops_hit
  s_pop_left_active:
    - pops_hit

  player_added{num == 2}: show_player_2_added
  player_added{num == 3}: show_player_3_added
  player_added{num == 4}: show_player_4_added

  s_left_drops_1_active{current_player.villain_mode_running != 1}:
    - drop_hit_no_mode
  s_left_drops_2_active{current_player.villain_mode_running != 1}:
    - drop_hit_no_mode
  s_left_drops_3_active{current_player.villain_mode_running != 1}:
    - drop_hit_no_mode

  s_right_drops_1_active{current_player.villain_mode_running != 1}:
    - drop_hit_no_mode
  s_right_drops_2_active{current_player.villain_mode_running != 1}:
    - drop_hit_no_mode
  s_right_drops_3_active{current_player.villain_mode_running != 1}:
    - drop_hit_no_mode
  s_right_drops_4_active{current_player.villain_mode_running != 1}:
    - drop_hit_no_mode
  s_right_drops_5_active{current_player.villain_mode_running != 1}:
    - drop_hit_no_mode



sound_player:
  s_web_spinner_active{mode.super_spinner.active == False}:
    rope_1:
      action: play
      bus: effects

  s_outlane_r_active{current_player.ball_save_count == 0}:
    jj_end_of_the_line:
      action: play
      bus: voice

  s_outlane_l_active{current_player.ball_save_count == 0}:
    jj_spiderman_caught:
      action: play
      bus: voice

  secondary_switch_hit:
    hb_blip_1:
      action: play
      bus: effects

  pops_hit:
    hb_pot_1:
      action: play
      bus: effects

  drop_hit_no_mode:
    throwing_star:
      action: play
      bus: effects




widget_player:
  show_player_2_added:
    player_2_added_widget:
      action: play
      expire: 2s

  show_player_3_added:
    player_3_added_widget:
      action: play
      expire: 2s

  show_player_4_added:
    player_4_added_widget:
      action: play
      expire: 2s


slide_player:
  mode_base_started:
    main_game:
      action: play
    attract:
      action: remove

timers:
  timer_up_post_hold:
    start_value: 0
    end_value: 6
    tick_interval: 1s
    control_events:
      - action: restart
        event: enable_up_post_event
        
light_player:
  mode_base_started:
    gi:
      color: E0E0E0        
  ramp_raise:
    gi:
      color: F0F000        
  ramp_lower:
    gi:
      color: F00000        
  s_upper_exit_left_opto_active:
    gi:
      color: E0E0E0        
  s_upper_exit_right_opto_active:
    gi:
      color: E0E0E0        
      
