#config_version=6

mode:
  start_events: start_mode_human_flies
  stop_events:
    - human_flies_mode_complete
    - human_flies_mode_completed_summary
    - ball_ended
  code: human_flies.HumanFlies
  priority: 500

multiballs:
  human_flies_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 10s
    start_events: human_flies_start_multiball
    stop_events:
      - human_flies_mode_completed_summary
      - ball_ended

  human_flies_more_time_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 20s
    start_events: human_flies_start_more_time_multiball
    stop_events:
      - human_flies_mode_completed_summary
      - ball_ended

variable_player:
  multiball_human_flies_multiball_started:
    multiball_autoplunge_active:
      action: set
      int: 1

  multiball_human_flies_more_time_multiball_started:
    multiball_autoplunge_active:
      action: set
      int: 1

  multiball_human_flies_multiball_ended:
    multiball_autoplunge_active:
      action: set
      int: 0

  multiball_human_flies_more_time_multiball_ended:
    multiball_autoplunge_active:
      action: set
      int: 0

widget_player:
  mode_human_flies_started:
    human_flies:
      action: play

  human_flies_mode_complete:
    human_flies:
      action: remove

  mode_human_flies_stopping:
    human_flies:
      action: remove

event_player:
  mode_human_flies_started:
    - clear_saucers_delayed
    - human_flies_clear_all_lights

  mode_human_flies_stopping:
    - clear_saucers_delayed
    - human_flies_clear_all_lights

  human_flies_mode_complete:
    villain_bookend_summary_request:
      villain: human_flies
      done_event: human_flies_mode_completed_summary

  multiball_human_flies_multiball_ended:
    - human_flies_multiball_ended

  multiball_human_flies_more_time_multiball_ended:
    - human_flies_multiball_ended

  s_upper_target_left_active:
    - human_flies_upper_target_left_hit

  s_upper_target_center_active:
    - human_flies_upper_target_center_hit

  s_upper_target_right_active:
    - human_flies_upper_target_right_hit

  s_trispinner_opto_active:
    - human_flies_upper_spinner_hit

  s_saucer_1_active:
    - human_flies_saucer_1_hit

  s_saucer_2_active:
    - human_flies_saucer_2_hit

  s_saucer_3_active:
    - human_flies_saucer_3_hit

  drop_target_bank_dt_bank_left_down:
    - drop_target_bank_dt_bank_left_reset

  drop_target_bank_dt_bank_right_down:
    - drop_target_bank_dt_bank_right_reset

light_player:
  human_flies_clear_all_lights:
    l_upper_left: off
    l_upper_middle: off
    l_upper_right: off
    l_1: off
    l_2: off
    l_3: off
    l_spinner: off

  human_flies_round_started:
    l_upper_left: yellow
    l_upper_middle: yellow
    l_upper_right: yellow
    l_spinner: yellow

  human_flies_round_reset:
    l_upper_left: yellow
    l_upper_middle: yellow
    l_upper_right: yellow
    l_1: off
    l_2: off
    l_3: off

  human_flies_upper_left_complete:
    l_upper_left: green

  human_flies_upper_center_complete:
    l_upper_middle: green

  human_flies_upper_right_complete:
    l_upper_right: green

  human_flies_saucer_1_lit:
    l_1: yellow

  human_flies_saucer_2_lit:
    l_2: yellow

  human_flies_saucer_3_lit:
    l_3: yellow

  human_flies_shot_assist_used:
    l_upper_left: green
    l_upper_middle: green
    l_upper_right: green
    l_1: yellow
    l_2: yellow
    l_3: yellow

  human_flies_super_jackpot_collected:
    l_1: white
    l_2: white
    l_3: white
