#config_version=6

mode:
  start_events: start_mode_desperado
  stop_events:
    - desperado_mode_completed_summary
    - ball_ended
  priority: 300
  code: desperado.Desperado

event_player:
  mode_desperado_started:
    - desperado_setup
    - rooftop_diverter_close

  desperado_setup:
    - drop_target_bank_dt_bank_left_reset
    - drop_target_bank_dt_bank_right_reset|100ms
    - clear_saucers_delayed
    - desperado_mode_intro

  mode_desperado_stopping:
    - desperado_clear_lights
    - clear_saucers

  s_right_drops_1_active: desperado_right_drop_1_hit
  s_right_drops_2_active: desperado_right_drop_2_hit
  s_right_drops_3_active: desperado_right_drop_3_hit
  s_right_drops_4_active: desperado_right_drop_4_hit
  s_right_drops_5_active: desperado_right_drop_5_hit

  drop_target_bank_dt_bank_left_down: desperado_left_bank_complete

  s_saucer_1_active: delayed_kickout_saucer_1
  s_saucer_2_active: delayed_kickout_saucer_2
  s_saucer_3_active: delayed_kickout_saucer_3
  s_vuk_switch_active: up_kick

widget_player:
  mode_desperado_started:
    desperado:
      action: play
  desperado_mode_complete:
    desperado:
      action: remove
  mode_desperado_stopping:
    desperado:
      action: remove

light_player:
  mode_desperado_started:
    gi: 70C8FF
  mode_desperado_stopping:
    gi: E0E0E0
  desperado_clear_lights:
    l_5bank_1: off
    l_5bank_2: off
    l_5bank_3: off
    l_5bank_4: off
    l_5bank_5: off
  desperado_target_1_complete:
    l_5bank_1: green
  desperado_target_2_complete:
    l_5bank_2: green
  desperado_target_3_complete:
    l_5bank_3: green
  desperado_target_4_complete:
    l_5bank_4: green
  desperado_target_5_complete:
    l_5bank_5: green
  desperado_extra_round_started:
    l_5bank_1: green
    l_5bank_2: green
    l_5bank_3: green
    l_5bank_4: green
    l_5bank_5: green

show_player:
  desperado_round_started:
    desperado_left_bank_time_show: {action: play, loops: -1, speed: 2}
  desperado_target_1_available:
    desperado_right_drop_1_available_show: {action: play, loops: -1, speed: 2}
  desperado_target_2_available:
    desperado_right_drop_2_available_show: {action: play, loops: -1, speed: 2}
  desperado_target_3_available:
    desperado_right_drop_3_available_show: {action: play, loops: -1, speed: 2}
  desperado_target_4_available:
    desperado_right_drop_4_available_show: {action: play, loops: -1, speed: 2}
  desperado_target_5_available:
    desperado_right_drop_5_available_show: {action: play, loops: -1, speed: 2}
  desperado_target_1_complete:
    desperado_right_drop_1_available_show: {action: stop}
  desperado_target_2_complete:
    desperado_right_drop_2_available_show: {action: stop}
  desperado_target_3_complete:
    desperado_right_drop_3_available_show: {action: stop}
  desperado_target_4_complete:
    desperado_right_drop_4_available_show: {action: stop}
  desperado_target_5_complete:
    desperado_right_drop_5_available_show: {action: stop}
  desperado_escape_started:
    desperado_right_drop_1_available_show: {action: stop}
    desperado_right_drop_2_available_show: {action: stop}
    desperado_right_drop_3_available_show: {action: stop}
    desperado_right_drop_4_available_show: {action: stop}
    desperado_right_drop_5_available_show: {action: stop}
  desperado_extra_round_started:
    desperado_right_drop_1_available_show: {action: play, loops: -1, speed: 3}
    desperado_right_drop_2_available_show: {action: play, loops: -1, speed: 3}
    desperado_right_drop_3_available_show: {action: play, loops: -1, speed: 3}
    desperado_right_drop_4_available_show: {action: play, loops: -1, speed: 3}
    desperado_right_drop_5_available_show: {action: play, loops: -1, speed: 3}
  desperado_clear_lights:
    desperado_right_drop_1_available_show: {action: stop}
    desperado_right_drop_2_available_show: {action: stop}
    desperado_right_drop_3_available_show: {action: stop}
    desperado_right_drop_4_available_show: {action: stop}
    desperado_right_drop_5_available_show: {action: stop}
    desperado_left_bank_time_show: {action: stop}

shows:
  desperado_right_drop_1_available_show:
    - duration: 250ms
      lights: {l_5bank_1: green}
    - duration: 250ms
      lights: {l_5bank_1: "003000"}
  desperado_right_drop_2_available_show:
    - duration: 250ms
      lights: {l_5bank_2: green}
    - duration: 250ms
      lights: {l_5bank_2: "003000"}
  desperado_right_drop_3_available_show:
    - duration: 250ms
      lights: {l_5bank_3: green}
    - duration: 250ms
      lights: {l_5bank_3: "003000"}
  desperado_right_drop_4_available_show:
    - duration: 250ms
      lights: {l_5bank_4: green}
    - duration: 250ms
      lights: {l_5bank_4: "003000"}
  desperado_right_drop_5_available_show:
    - duration: 250ms
      lights: {l_5bank_5: green}
    - duration: 250ms
      lights: {l_5bank_5: "003000"}
  desperado_left_bank_time_show:
    - duration: 400ms
      lights: {l_3bankbonus: blue}
    - duration: 400ms
      lights: {l_3bankbonus: off}
