#config_version=6

mode:
  start_events: start_mode_doc_ock
  stop_events:
    - doc_ock_mode_complete
    - doc_ock_mode_completed_summary
    - ball_ended
  code: doc_ock.doc_ock
  priority: 600


variable_player:
  doc_ock_jackpot_award:
    score: current_player.doc_ock_last_jackpot



widget_player:
  xxx_doc_ock_next_jackpot_changed:
    doc_ock_next_jackpot:
      action: play

  xxx_doc_ock_spinner_multiplier_increased:
    doc_ock_next_jackpot:
      action: play
      expire: 2s

  xxx_doc_ock_arm_locked_score:
    doc_ock_next_jackpot:
      action: play
      expire: 2s

  doc_ock_jackpot_award:
    jackpot_collected:
      action: play
      expire: 2s

  mode_doc_ock_started:
    doc_ock:
      action: play

  doc_ock_mode_complete:
    doc_ock:
      action: remove


event_player:
  drop_target_bank_dt_bank_left_down:
    - drop_target_bank_dt_bank_left_reset

  drop_target_bank_dt_bank_right_down:
    - drop_target_bank_dt_bank_right_reset

  doc_ock_startup_complete:
    - doc_ock_start_arms
    - reset_drops|1s
    - clear_saucers

  s_left_flipper_active:
    - doc_ock_rotate_left

  s_right_flipper_active:
    - doc_ock_rotate_right

  s_outlane_l_active:
    - doc_ock_arm_1_hit

  s_inlane_l_active:
    - doc_ock_arm_2_hit

  s_inlane_r_active:
    - doc_ock_arm_3_hit

  s_outlane_r_active:
    - doc_ock_arm_4_hit

  s_web_spinner_active:
    - doc_ock_spinner_hit

  s_web_target_left_active:
    - doc_ock_jackpot_request

  s_web_target_top_active:
    - doc_ock_jackpot_request

  s_saucer_1_active:
    - doc_ock_breakout_1_request
    - clear_saucers

  s_saucer_2_active:
    - doc_ock_breakout_2_request
    - clear_saucers

  s_saucer_3_active:
    - doc_ock_breakout_3_request
    - clear_saucers

  s_star_rollover_active:
    - doc_ock_breakout_4_request

  s_inlane_a_active:
    - doc_ock_breakout_5_request

  s_inlane_b_active:
    - doc_ock_breakout_6_request


sound_player:
  doc_ock_breakout_hit:
    arm_powerup:
      action: play
      bus: effects

  doc_ock_arm_locked_score:
    arm_powerdown:
      action: play
      bus: effects

  doc_ock_jackpot_not_lit:
    hb_blip_1:
      action: play
      bus: effects

  doc_ock_jackpot_award:
    drum_1:
      action: play
      bus: effects


show_player:
  doc_ock_arm_1_pulse:
    doc_ock_arm_1_solid:
      action: stop
    doc_ock_arm_1_pulse:
      loops: -1

  doc_ock_arm_2_pulse:
    doc_ock_arm_2_solid:
      action: stop
    doc_ock_arm_2_pulse:
      loops: -1

  doc_ock_arm_3_pulse:
    doc_ock_arm_3_solid:
      action: stop
    doc_ock_arm_3_pulse:
      loops: -1

  doc_ock_arm_4_pulse:
    doc_ock_arm_4_solid:
      action: stop
    doc_ock_arm_4_pulse:
      loops: -1

  doc_ock_arm_1_solid:
    doc_ock_arm_1_pulse:
      action: stop
    doc_ock_arm_1_solid:
      loops: -1

  doc_ock_arm_2_solid:
    doc_ock_arm_2_pulse:
      action: stop
    doc_ock_arm_2_solid:
      loops: -1

  doc_ock_arm_3_solid:
    doc_ock_arm_3_pulse:
      action: stop
    doc_ock_arm_3_solid:
      loops: -1

  doc_ock_arm_4_solid:
    doc_ock_arm_4_pulse:
      action: stop
    doc_ock_arm_4_solid:
      loops: -1


  doc_ock_jackpot_lit:
    doc_ock_web_jackpot_show:
      loops: -1

  doc_ock_jackpot_award:
    doc_ock_web_jackpot_show:
      action: stop
    doc_ock_jackpot_collect_show:
      loops: 1


  doc_ock_breakout_1_lit:
    doc_ock_breakout_1_show:
      loops: -1

  doc_ock_breakout_2_lit:
    doc_ock_breakout_2_show:
      loops: -1

  doc_ock_breakout_3_lit:
    doc_ock_breakout_3_show:
      loops: -1

  doc_ock_breakout_4_lit:
    doc_ock_breakout_4_show:
      loops: -1

  doc_ock_breakout_5_lit:
    doc_ock_breakout_5_show:
      loops: -1

  doc_ock_breakout_6_lit:
    doc_ock_breakout_6_show:
      loops: -1


  doc_ock_mode_complete:
    doc_ock_arm_1_pulse:
      action: stop
    doc_ock_arm_2_pulse:
      action: stop
    doc_ock_arm_3_pulse:
      action: stop
    doc_ock_arm_4_pulse:
      action: stop
    doc_ock_web_jackpot_show:
      action: stop
    doc_ock_breakout_1_show:
      action: stop
    doc_ock_breakout_2_show:
      action: stop
    doc_ock_breakout_3_show:
      action: stop
    doc_ock_breakout_4_show:
      action: stop
    doc_ock_breakout_5_show:
      action: stop
    doc_ock_breakout_6_show:
      action: stop
    doc_ock_complete_show:
      loops: 1

shows:
  doc_ock_arm_1_pulse:
    - duration: 200ms
      lights:
        l_left_outlane: 202060
    - duration: 200ms
      lights:
        l_left_outlane: 2020C0

  doc_ock_arm_2_pulse:
    - duration: 200ms
      lights:
        l_left_inlane: 202060
    - duration: 200ms
      lights:
        l_left_inlane: 2020C0

  doc_ock_arm_3_pulse:
    - duration: 200ms
      lights:
        l_right_inlane: 202060
    - duration: 200ms
      lights:
        l_right_inlane: 2020C0

  doc_ock_arm_4_pulse:
    - duration: 200ms
      lights:
        l_right_outlane: 202060
    - duration: 200ms
      lights:
        l_right_outlane: 2020C0

  doc_ock_arm_1_solid:
    - duration: 400ms
      lights:
        l_left_outlane: white
    - duration: 400ms
      lights:
        l_left_outlane: 20D0D0

  doc_ock_arm_2_solid:
    - duration: 400ms
      lights:
        l_left_inlane: white
    - duration: 400ms
      lights:
        l_left_inlane: 20D0D0

  doc_ock_arm_3_solid:
    - duration: 400ms
      lights:
        l_right_inlane: white
    - duration: 400ms
      lights:
        l_right_inlane: 20D0D0

  doc_ock_arm_4_solid:
    - duration: 400ms
      lights:
        l_right_outlane: white
    - duration: 400ms
      lights:
        l_right_outlane: 20D0D0

  doc_ock_web_jackpot_show:
    - duration: 250ms
      lights:
        l_left_web_target: purple
        l_mid_spider_target: purple
    - duration: 250ms
      lights:
        l_left_web_target: white
        l_mid_spider_target: white

  doc_ock_jackpot_collect_show:
    - duration: 150ms
      lights:
        gi: purple
    - duration: 150ms
      lights:
        gi: white

  doc_ock_breakout_1_show:
    - duration: 250ms
      lights:
        l_1_hole_l: red
        l_1_hole_r: red        
    - duration: 250ms
      lights:
        l_1_hole_l: off
        l_1_hole_r: off        

  doc_ock_breakout_2_show:
    - duration: 250ms
      lights:
        l_2_hole_l: red
        l_2_hole_r: red        
    - duration: 250ms
      lights:
        l_2_hole_l: off
        l_2_hole_r: off        

  doc_ock_breakout_3_show:
    - duration: 250ms
      lights:
        l_3_hole_l: red
        l_3_hole_r: red        
    - duration: 250ms
      lights:
        l_3_hole_l: off
        l_3_hole_r: off        

  doc_ock_breakout_4_show:
    - duration: 250ms
      lights:
        l_star: red
    - duration: 250ms
      lights:
        l_star: off        

  doc_ock_breakout_5_show:
    - duration: 250ms
      lights:
        l_a_rollover: red
    - duration: 250ms
      lights:
        l_a_rollover: off        

  doc_ock_breakout_6_show:
    - duration: 250ms
      lights:
        l_b_rollover: red
    - duration: 250ms
      lights:
        l_b_rollover: off        

  doc_ock_breakout_hit_show:
    - duration: 500ms
      lights:
        gi: red
    - duration: 500ms
      lights:
        gi: purple

  doc_ock_complete_show:
    - duration: 200ms
      lights:
        gi: red
    - duration: 200ms
      lights:
        gi: off
        
