#config_version=6

mode:
  start_events: ball_started
  priority: 90



extra_balls:
  mystery_extra_ball:
    group: main_extra_ball_group


widget_player:
  mystery_extra_ball_lit:
    extra_ball_lit:
      expire: 3s
      priority: 1000
      action: play

  mystery_extra_ball_award:
    extra_ball:
      expire: 7s
      priority: 1000
      action: play

  show_ball_saved_widget:
    ball_saved:
      expire: 3s
      priority: 1200
      action: play



sound_player:
  mystery_extra_ball_award:
    sm_extra_ball: 
      action: play
      bus: voice

  mystery_extra_ball_lit:
    sm_extra_ball_is_lit: 
      action: play
      bus: voice

  mystery_right_extra_ball_lit:
    sm_extra_ball_is_lit: 
      action: play
      bus: voice

event_player:
 
  #directly from bugle
  mystery_award_award_extra_ball:
    - mystery_extra_ball_award

  #light the eb at left bank
  mystery_award_light_extra_ball:
    - mystery_extra_ball_lit

  #light the eb at right bank
  mystery_award_light_right_extra_ball:
    - mystery_right_extra_ball_lit

  #left bank complete when lit
  drop_target_bank_dt_bank_left_down{current_player.extra_ball_is_lit == 1}:
    - mystery_left_extra_ball_award
    - mystery_extra_ball_award

  #right bank complete when lit
  drop_target_bank_dt_bank_right_down{current_player.extra_ball_right_is_lit == 1}:
    - mystery_right_extra_ball_award
    - mystery_extra_ball_award

  ball_save_default_ball_save_enabled:
    - increase_ballsave_count
  ball_save_mystery_ball_save_enabled:
    - increase_ballsave_count
  ball_save_case_file_ball_save_enabled:
    - increase_ballsave_count
  ball_save_outlane_add_a_ball_save_enabled:
    - increase_ballsave_count
  ball_save_chapter_select_ball_save_enabled:
    - increase_ballsave_count

  ball_save_default_ball_save_saving_ball:
    saved_ball_pending_plunger:
    show_ball_saved_widget:
      save_type: default
      title: BALL SAVED
      subtitle: DEFAULT SAVE

  ball_save_mystery_ball_save_saving_ball:
    saved_ball_pending_plunger:
    show_ball_saved_widget:
      save_type: mystery
      title: BALL SAVED
      subtitle: DAILY BUGLE SAVE

  ball_save_case_file_ball_save_saving_ball:
    saved_ball_pending_plunger:
    show_ball_saved_widget:
      save_type: safety_net
      title: BALL SAVED
      subtitle: SAFETY NET

  ball_save_outlane_add_a_ball_save_saving_ball:
    outlane_add_a_ball_pending_plunger:
    show_ball_saved_widget:
      save_type: outlane
      title: BALL SAVED
      subtitle: OUTLANE SAVE

  ball_save_chapter_select_ball_save_saving_ball:
    saved_ball_pending_plunger:

  show_ball_saved_safety_net:
    show_ball_saved_widget:
      save_type: safety_net
      title: BALL SAVED
      subtitle: SAFETY NET

  show_ball_saved_multiball:
    show_ball_saved_widget:
      save_type: multiball
      title: BALL SAVED
      subtitle: MULTIBALL SAVE

  ball_save_default_ball_save_disabled{current_player.ball_save_count > 0}:
    - decrease_ballsave_count
  ball_save_mystery_ball_save_disabled{current_player.ball_save_count > 0}:
    - decrease_ballsave_count
  ball_save_case_file_ball_save_disabled{current_player.ball_save_count > 0}:
    - decrease_ballsave_count
  ball_save_outlane_add_a_ball_save_disabled{current_player.ball_save_count > 0}:
    - decrease_ballsave_count
  ball_save_chapter_select_ball_save_disabled{current_player.ball_save_count > 0}:
    - decrease_ballsave_count





variable_player:
  increase_ballsave_count:
    ball_save_count:
      action: set
      int: current_player.ball_save_count+1

  decrease_ballsave_count:
    ball_save_count:
      action: set
      int: current_player.ball_save_count-1

  saved_ball_pending_plunger:
    saved_ball_pending_plunger:
      action: set
      int: 1

  saved_ball_arrived_at_plunger:
    saved_ball_pending_plunger:
      action: set
      int: 0
    saved_ball_in_plunger:
      action: set
      int: 1

  clear_saved_ball_in_plunger:
    saved_ball_in_plunger:
      action: set
      int: 0

  outlane_add_a_ball_pending_plunger:
    outlane_add_a_ball_pending_plunger:
      action: set
      int: 1

  outlane_add_a_ball_arrived_at_plunger:
    outlane_add_a_ball_pending_plunger:
      action: set
      int: 0
    outlane_add_a_ball_in_plunger:
      action: set
      int: 1

  clear_outlane_add_a_ball_in_plunger:
    outlane_add_a_ball_in_plunger:
      action: set
      int: 0

  mode_extra_ball_started:
    saved_ball_pending_plunger:
      action: set
      int: 0
    saved_ball_in_plunger:
      action: set
      int: 0
    outlane_add_a_ball_pending_plunger:
      action: set
      int: 0
    outlane_add_a_ball_in_plunger:
      action: set
      int: 0

  #if points instead of eb - TODO - call this from somewhere else
  extra_ball_award_million_points:
    score: 1000000

  mystery_extra_ball_lit:
    extra_ball_is_lit:
      action: set
      int: 1

  mystery_right_extra_ball_lit:
    extra_ball_right_is_lit:
      action: set
      int: 1

  mystery_left_extra_ball_award:
    extra_ball_is_lit:
      action: set
      int: 0

  mystery_right_extra_ball_award:
    extra_ball_right_is_lit:
      action: set
      int: 0


show_player:

  mystery_extra_ball_lit:
    extra_ball_lit_show:
      loops: -1

  mystery_right_extra_ball_lit:
    extra_ball_right_lit_show:
      loops: -1

  mystery_extra_ball_award:
    extra_ball_lit_show:
      action: stop
    extra_ball_collect_gi_show:
      loops: 6
    extra_ball_award_show:
      loops: 1

  mystery_right_extra_ball_award:
    extra_ball_right_lit_show:
      action: stop
    extra_ball_collect_gi_show:
      loops: 4
    extra_ball_right_award_show:
      loops: 1

#todo:  flash shoot again light during goblin, vulture, parafino MBs  - find events from logs

  ball_save_default_ball_save_enabled:
    shoot_again_flash:
      loops: -1

  ball_save_default_ball_save_hurry_up:
    shoot_again_fast_flash:
      loops: -1

  ball_save_default_ball_save_disabled:
    shoot_again_flash:
      action: stop
    shoot_again_fast_flash:
      action: stop

  ball_save_mystery_ball_save_enabled:
    shoot_again_flash:
      loops: -1

  ball_save_mystery_ball_save_hurry_up:
    shoot_again_fast_flash:
      loops: -1

  ball_save_mystery_ball_save_disabled:
    shoot_again_flash:
      action: stop
    shoot_again_fast_flash:
      action: stop

  ball_save_case_file_ball_save_enabled:
    shoot_again_flash:
      loops: -1

  ball_save_case_file_ball_save_hurry_up:
    shoot_again_fast_flash:
      loops: -1

  ball_save_case_file_ball_save_disabled:
    shoot_again_flash:
      action: stop
    shoot_again_fast_flash:
      action: stop


shows:
  shoot_again_fast_flash:
    - duration: 250ms
      lights:
        l_shoot_again: white
    - duration: 250ms
      lights:
        l_shoot_again: off     

  shoot_again_flash:
    - duration: 500ms
      lights:
        l_shoot_again: white
    - duration: 500ms
      lights:
        l_shoot_again: off     
      
  extra_ball_collect_gi_show:
    - duration: 250ms
      lights:
        gi: white
    - duration: 250ms
      lights:
        gi: blue

  extra_ball_lit_show:
    - duration: 200ms
      lights:
        l_extraball: white
    - duration: 200ms
      lights:
        l_extraball: red

  extra_ball_award_show:
    - duration: -1
      lights:
        l_shoot_again: white
        gi: white
        
  extra_ball_right_lit_show:
    - duration: 200ms
      lights:
        l_right_extraball: white
    - duration: 200ms
      lights:
        l_right_extraball: red

  extra_ball_right_award_show:
    - duration: -1
      lights:
        l_shoot_again: white
        gi: white
