#config_version=6

mode:
  start_events: start_mode_parafino
  stop_events:
    - parafino_mode_completed_summary
    - ball_ended
  priority: 800
  code: parafino.Parafino

variable_player:

  multiball_parafino_multiball_started:
    multiball_autoplunge_active:
      action: set
      int: 1

  multiball_parafino_multiball_ended:
    multiball_autoplunge_active:
      action: set
      int: 0

#multiballs:
#  parafino_multiball:
#    ball_count: 2
#    ball_count_type: total
#    shoot_again: 20s
#    start_events: parafino_start_multiball
#    stop_events:
#      - parafino_stop_multiball

#  parafino_add_a_ball:
#    ball_count: 1
#    ball_count_type: add
#    shoot_again: 10s
#    start_events: parafino_add_a_ball

multiballs:
  parafino_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 20s
    start_events: parafino_start_multiball
    add_a_ball_events:
      - parafino_add_a_ball
    add_a_ball_shoot_again: 10s
    add_a_ball_hurry_up_time: 3s
    stop_events:
      - parafino_stop_multiball

event_player:
  parafino_startup_complete:
    - parafino_setup
    - parafino_start_multiball|1s

  parafino_setup:
    - clear_saucers
    - drop_target_bank_dt_bank_left_reset
    - drop_target_bank_dt_bank_right_reset
    - parafino_clear_all_lights
    - parafino_mode_intro

  multiball_parafino_multiball_ended:
    - parafino_multiball_ended

  mode_parafino_stopping:
    - parafino_clear_all_lights
    - clear_saucers


widget_player:
  mode_parafino_started:
    parafino:
      action: play

  parafino_mode_completed_summary:
    parafino:
      action: remove

  xparafino_mode_intro:
    parafino_intro:
      action: play
      expire: 5s

  xparafino_jackpot_lit:
    parafino_jackpot_lit:
      action: play
      expire: 3s

  xparafino_jackpot_collected:
    parafino_jackpot_collected:
      action: play
      expire: 3s

  xparafino_all_jackpots_collected:
    parafino_heat_cycle_complete:
      action: play
      expire: 4s

show_player:

  parafino_clear_all_lights:
    parafino_gi_heat_0:
      action: stop
    parafino_gi_heat_1:
      action: stop
    parafino_gi_heat_2:
      action: stop
    parafino_gi_heat_3:
      action: stop
    parafino_gi_heat_4:
      action: stop
    parafino_gi_heat_5:
      action: stop
    parafino_left_jackpot_show:
      action: stop
    parafino_pops_jackpot_show:
      action: stop
    parafino_right_jackpot_show:
      action: stop

  parafino_gi_set_heat_0:
    parafino_gi_heat_0:
      action: play
      loops: -1

  parafino_gi_set_heat_1:
    parafino_gi_heat_1:
      action: play
      loops: -1

  parafino_gi_set_heat_2:
    parafino_gi_heat_2:
      action: play
      loops: -1

  parafino_gi_set_heat_3:
    parafino_gi_heat_3:
      action: play
      loops: -1

  parafino_gi_set_heat_4:
    parafino_gi_heat_4:
      action: play
      loops: -1

  parafino_gi_set_heat_5:
    parafino_gi_heat_5:
      action: play
      loops: -1

  parafino_gi_flash_heat_0:
    parafino_gi_heat_0:
      action: play
      loops: 0

  parafino_gi_flash_heat_1:
    parafino_gi_heat_1:
      action: play
      loops: 0

  parafino_gi_flash_heat_2:
    parafino_gi_heat_2:
      action: play
      loops: 0

  parafino_gi_flash_heat_3:
    parafino_gi_heat_3:
      action: play
      loops: 0

  parafino_gi_flash_heat_4:
    parafino_gi_heat_4:
      action: play
      loops: 0

  parafino_gi_flash_heat_5:
    parafino_gi_heat_5:
      action: play
      loops: 0

  parafino_left_jackpot_lit:
    parafino_left_jackpot_show:
      action: play
      loops: -1
      speed: 3

  parafino_pops_jackpot_lit:
    parafino_pops_jackpot_show:
      action: play
      loops: -1
      speed: 3

  parafino_right_jackpot_lit:
    parafino_right_jackpot_show:
      action: play
      loops: -1
      speed: 3

  parafino_clear_jackpot_lights:
    parafino_left_jackpot_show:
      action: stop
    parafino_pops_jackpot_show:
      action: stop
    parafino_right_jackpot_show:
      action: stop

  parafino_heat_cycle_reset:
    parafino_left_jackpot_show:
      action: stop
    parafino_pops_jackpot_show:
      action: stop
    parafino_right_jackpot_show:
      action: stop

shows:

  parafino_gi_heat_0:
    - duration: 500ms
      lights:
        gi: 6ecbff
    - duration: 500ms
      lights:
        gi: 9edcff

  parafino_gi_heat_1:
    - duration: 500ms
      lights:
        gi: bfeeff
    - duration: 500ms
      lights:
        gi: e6f9ff

  parafino_gi_heat_2:
    - duration: 500ms
      lights:
        gi: white
    - duration: 500ms
      lights:
        gi: e8f8ff

  parafino_gi_heat_3:
    - duration: 500ms
      lights:
        gi: fff1cf
    - duration: 500ms
      lights:
        gi: ffe6a3

  parafino_gi_heat_4:
    - duration: 500ms
      lights:
        gi: orange
    - duration: 500ms
      lights:
        gi: ff8c00

  parafino_gi_heat_5:
    - duration: 500ms
      lights:
        gi: red
    - duration: 500ms
      lights:
        gi: ff3300

  parafino_left_jackpot_show:
    - duration: 200ms
      lights:
        l_3bankbonus: red
    - duration: 200ms
      lights:
        l_3bankbonus: off
    - duration: 200ms
      lights:
        l_1: green
    - duration: 200ms
      lights:
        l_1: off

  parafino_pops_jackpot_show:
    - duration: 200ms
      lights:
        l_pop_1_1: red
        l_pop_1_2: red
        l_pop_1_3: red
        l_pop_1_4: red
        l_pop_1_5: red
        l_pop_1_6: red
        l_pop_1_7: red
        l_pop_1_8: red
        l_pop_1_9: red
        l_pop_1_10: red
        l_pop_1_11: red
        l_pop_1_12: red
        l_pop_2_1: red
        l_pop_2_2: red
        l_pop_2_3: red
        l_pop_2_4: red
        l_pop_2_5: red
        l_pop_2_6: red
        l_pop_2_7: red
        l_pop_2_8: red
        l_pop_2_9: red
        l_pop_2_10: red
        l_pop_2_11: red
        l_pop_2_12: red
    - duration: 200ms
      lights:
        l_pop_1_1: off
        l_pop_1_2: off
        l_pop_1_3: off
        l_pop_1_4: off
        l_pop_1_5: off
        l_pop_1_6: off
        l_pop_1_7: off
        l_pop_1_8: off
        l_pop_1_9: off
        l_pop_1_10: off
        l_pop_1_11: off
        l_pop_1_12: off
        l_pop_2_1: off
        l_pop_2_2: off
        l_pop_2_3: off
        l_pop_2_4: off
        l_pop_2_5: off
        l_pop_2_6: off
        l_pop_2_7: off
        l_pop_2_8: off
        l_pop_2_9: off
        l_pop_2_10: off
        l_pop_2_11: off
        l_pop_2_12: off
    - duration: 200ms
      lights:
        l_2: green
    - duration: 200ms
      lights:
        l_2: off

  parafino_right_jackpot_show:
    - duration: 200ms
      lights:
        l_5bank_1: red
        l_5bank_2: red
        l_5bank_3: red
        l_5bank_4: red
        l_5bank_5: red
    - duration: 200ms
      lights:
        l_5bank_1: off
        l_5bank_2: off
        l_5bank_3: off
        l_5bank_4: off
        l_5bank_5: off
    - duration: 200ms
      lights:
        l_3: green
    - duration: 200ms
      lights:
        l_3: off
