#config_version=6

mode:
  start_events: start_mode_dr_zapp
  stop_events:
    - dr_zapp_mode_complete
    - dr_zapp_mode_completed_summary
    - ball_ended
  code: dr_zapp.DrZapp
  priority: 300

widget_player:
  mode_dr_zapp_started:
    dr_zapp: {action: play}
  dr_zapp_mode_complete:
    dr_zapp: {action: remove}
  mode_dr_zapp_stopping:
    dr_zapp: {action: remove}

event_player:
  s_left_drops_1_active: dr_zapp_left_bank_hit
  s_left_drops_2_active: dr_zapp_left_bank_hit
  s_left_drops_3_active: dr_zapp_left_bank_hit
  s_right_drops_1_active: dr_zapp_right_bank_hit
  s_right_drops_2_active: dr_zapp_right_bank_hit
  s_right_drops_3_active: dr_zapp_right_bank_hit
  s_right_drops_4_active: dr_zapp_right_bank_hit
  s_right_drops_5_active: dr_zapp_right_bank_hit

  s_upper_target_left_active: dr_zapp_upper_target_left
  s_upper_target_center_active: dr_zapp_upper_target_center
  s_upper_target_right_active: dr_zapp_upper_target_right

  s_trispinner_opto_active: dr_zapp_spinner_hit
  s_upper_entrance_opto_active: dr_zapp_upper_entered

  drop_target_bank_dt_bank_left_down: drop_target_bank_dt_bank_left_reset
  drop_target_bank_dt_bank_right_down: drop_target_bank_dt_bank_right_reset

  mode_dr_zapp_started:
    - reset_drops
    - clear_saucers_delayed
  mode_dr_zapp_stopping:
    - clear_saucers_delayed
    - dr_zapp_clear_all
    - dr_zapp_disable_start_safety_net
    - dr_zapp_disable_upper_entry_save

ball_saves:
  dr_zapp_start_safety_net:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 1s
    enable_events: dr_zapp_enable_start_safety_net
    disable_events:
      - dr_zapp_disable_start_safety_net
      - mode_dr_zapp_stopping
      - ball_ending
    auto_launch: true
    balls_to_save: 1

  dr_zapp_upper_entry_save:
    active_time: 15s
    hurry_up_time: 3s
    grace_period: 1s
    enable_events: dr_zapp_enable_upper_entry_save
    disable_events:
      - dr_zapp_disable_upper_entry_save
      - mode_dr_zapp_stopping
      - ball_ending
    auto_launch: true
    balls_to_save: 1

show_player:
  dr_zapp_qualification_started:
    dr_zapp_dark_blue_gi: {loops: -1}
    dr_zapp_left_bank_pulse: {loops: -1}
    dr_zapp_right_bank_pulse: {loops: -1}

  dr_zapp_left_bank_qualified:
    dr_zapp_left_bank_pulse: {action: stop}
    dr_zapp_left_bank_solid: {loops: -1}
    dr_zapp_one_bank_gi: {loops: -1}

  dr_zapp_right_bank_qualified:
    dr_zapp_right_bank_pulse: {action: stop}
    dr_zapp_right_bank_solid: {loops: -1}
    dr_zapp_one_bank_gi: {loops: -1}

  dr_zapp_roof_open:
    dr_zapp_dark_blue_gi: {action: stop}
    dr_zapp_one_bank_gi: {action: stop}
    dr_zapp_roof_gi: {loops: -1}
    dr_zapp_upper_left_pulse: {loops: -1}
    dr_zapp_upper_center_pulse: {loops: -1}
    dr_zapp_upper_right_pulse: {loops: -1}

  dr_zapp_left_target_solid:
    dr_zapp_upper_left_pulse: {action: stop}
    dr_zapp_upper_left_solid: {loops: -1}
  dr_zapp_center_target_solid:
    dr_zapp_upper_center_pulse: {action: stop}
    dr_zapp_upper_center_solid: {loops: -1}
  dr_zapp_right_target_solid:
    dr_zapp_upper_right_pulse: {action: stop}
    dr_zapp_upper_right_solid: {loops: -1}

  dr_zapp_upper_target_collected:
    dr_zapp_target_white_flash: {loops: 1}
  dr_zapp_assisted_target_collected:
    dr_zapp_target_white_flash: {loops: 1}

  dr_zapp_defeated:
    dr_zapp_defeat_white_flash: {loops: 1}

  dr_zapp_bonus_started:
    dr_zapp_roof_gi: {action: stop}
    dr_zapp_bonus_gi: {loops: -1}

  dr_zapp_clear_all:
    dr_zapp_dark_blue_gi: {action: stop}
    dr_zapp_one_bank_gi: {action: stop}
    dr_zapp_roof_gi: {action: stop}
    dr_zapp_bonus_gi: {action: stop}
    dr_zapp_left_bank_pulse: {action: stop}
    dr_zapp_right_bank_pulse: {action: stop}
    dr_zapp_left_bank_solid: {action: stop}
    dr_zapp_right_bank_solid: {action: stop}
    dr_zapp_upper_left_pulse: {action: stop}
    dr_zapp_upper_center_pulse: {action: stop}
    dr_zapp_upper_right_pulse: {action: stop}
    dr_zapp_upper_left_solid: {action: stop}
    dr_zapp_upper_center_solid: {action: stop}
    dr_zapp_upper_right_solid: {action: stop}

light_player:
  dr_zapp_clear_all:
    gi: stop
    l_gi_3bank: stop
    l_gi_5bank_lower: stop
    l_gi_5bank_upper: stop
    l_upper_left: stop
    l_upper_middle: stop
    l_upper_right: stop

shows:
  dr_zapp_dark_blue_gi:
    - duration: 1s
      lights: {gi: 183060}
  dr_zapp_one_bank_gi:
    - duration: 500ms
      lights: {gi: 204080}
    - duration: 500ms
      lights: {gi: 102040}
  dr_zapp_roof_gi:
    - duration: 1s
      lights: {gi: 3090FF}
  dr_zapp_bonus_gi:
    - duration: 500ms
      lights: {gi: 3090FF}
    - duration: 500ms
      lights: {gi: FFFFFF}
  dr_zapp_target_white_flash:
    - duration: 250ms
      lights: {gi: FFFFFF}
    - duration: 250ms
      lights: {gi: 3090FF}
  dr_zapp_defeat_white_flash:
    - duration: 250ms
      lights: {gi: FFFFFF}
    - duration: 250ms
      lights: {gi: 3090FF}

  dr_zapp_left_bank_pulse:
    - duration: 500ms
      lights: {l_gi_3bank: 3080FF}
    - duration: 500ms
      lights: {l_gi_3bank: 102040}
  dr_zapp_right_bank_pulse:
    - duration: 500ms
      lights:
        l_gi_5bank_lower: 3080FF
        l_gi_5bank_upper: 3080FF
    - duration: 500ms
      lights:
        l_gi_5bank_lower: 102040
        l_gi_5bank_upper: 102040
  dr_zapp_left_bank_solid:
    - duration: 1s
      lights: {l_gi_3bank: 3080FF}
  dr_zapp_right_bank_solid:
    - duration: 1s
      lights:
        l_gi_5bank_lower: 3080FF
        l_gi_5bank_upper: 3080FF

  dr_zapp_upper_left_pulse:
    - duration: 500ms
      lights: {l_upper_left: FFFFFF}
    - duration: 500ms
      lights: {l_upper_left: 303030}
  dr_zapp_upper_center_pulse:
    - duration: 500ms
      lights: {l_upper_middle: FFFFFF}
    - duration: 500ms
      lights: {l_upper_middle: 303030}
  dr_zapp_upper_right_pulse:
    - duration: 500ms
      lights: {l_upper_right: FFFFFF}
    - duration: 500ms
      lights: {l_upper_right: 303030}
  dr_zapp_upper_left_solid:
    - duration: 1s
      lights: {l_upper_left: FFFFFF}
  dr_zapp_upper_center_solid:
    - duration: 1s
      lights: {l_upper_middle: FFFFFF}
  dr_zapp_upper_right_solid:
    - duration: 1s
      lights: {l_upper_right: FFFFFF}
