#config_version=6

mode:
  start_events: start_mode_goblin
  stop_events:
    - goblin_mode_ended
    - ball_ended
  code: goblin.Goblin
  priority: 500


multiballs:
  goblin_chaos_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 10s
    start_events: goblin_start_multiball
    stop_events:
      - goblin_stop_multiball
      - goblin_mode_ended
      - ball_ended


widget_player:
  mode_goblin_started:
    goblin:
      action: play

  goblin_mode_complete:
    goblin:
      action: remove


shots:
  gob_right_drop_1:
    switch: s_right_drops_1
  gob_right_drop_2:
    switch: s_right_drops_2
  gob_right_drop_3:
    switch: s_right_drops_3
  gob_right_drop_4:
    switch: s_right_drops_4
  gob_right_drop_5:
    switch: s_right_drops_5

  gob_left_drop_1:
    switch: s_left_drops_1
  gob_left_drop_2:
    switch: s_left_drops_2
  gob_left_drop_3:
    switch: s_left_drops_3

  gob_upper_target_left:
    switch: s_upper_target_left
  gob_upper_target_center:
    switch: s_upper_target_center
  gob_upper_target_right:
    switch: s_upper_target_right

shot_groups:
  gob_right_drops:
    shots: gob_right_drop_1, gob_right_drop_2, gob_right_drop_3, gob_right_drop_4, gob_right_drop_5

  gob_left_drops:
    shots: gob_left_drop_1, gob_left_drop_2, gob_left_drop_3

  gob_upper_targets:
    shots: gob_upper_target_left, gob_upper_target_center, gob_upper_target_right


event_player:
  mode_goblin_started:
    - reset_drops
    - goblin_start_multiball
    - clear_saucers

  multiball_goblin_chaos_multiball_ended:
    - goblin_mode_ended

  goblin_mode_ended:
    - goblin_stop_all_shows
    - reset_villain_locate

  goblin_hold_ended:
    - clear_saucers



  # real playfield input -> Python shot events
  s_left_web_target_active: goblin_left_web_hit
  s_web_target_top_active: goblin_right_web_hit
  s_web_spinner_active: goblin_spinner_hit
  gob_left_drops_hit: goblin_left_drops_hit
  gob_right_drops_hit: goblin_right_drops_hit
  s_trispinner_opto_active: goblin_upper_spinner_hit
  gob_upper_targets_hit: goblin_upper_target_hit
  # saucers also stabilize chaos
  s_saucer_1_active: 
    goblin_saucer_hit:
      saucer: 1
  s_saucer_2_active: 
    goblin_saucer_hit:
      saucer: 2
  s_saucer_3_active: 
    goblin_saucer_hit:
      saucer: 3

  # timers -> Python
  timer_goblin_flash_timer_complete:
    - goblin_flash_timer_complete

  timer_goblin_solid_timer_complete:
    - goblin_solid_timer_complete

  timer_goblin_hold_timer_complete:
    - goblin_hold_timer_complete

  ball_ending:
    - goblin_collect_bonus

variable_player:
  mode_goblin_started:
    goblin_chaos_bonus:
      action: set
      int: 0
    goblin_chaos_lock:
      action: set
      int: 0
    goblin_hold_count:
      action: set
      int: 0
    goblin_hold_active:
      action: set
      int: 0

  goblin_flashing_shot_score:
    score:
      action: add
      int: 50000
    goblin_chaos_bonus:
      action: add
      int: 50000

  goblin_solid_shot_score:
    score:
      action: add
      int: 2000

  goblin_collect_bonus:
    score:
      action: add
      int: current_player.goblin_chaos_bonus

  multiball_goblin_chaos_multiball_started:
    multiball_autoplunge_active:
      action: set
      int: 1

  multiball_goblin_chaos_multiball_ended:
    multiball_autoplunge_active:
      action: set
      int: 0

timers:
  goblin_flash_timer:
    start_value: 5
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: goblin_flash_timer_start
        action: restart
      - event: goblin_flash_timer_stop
        action: stop

  goblin_solid_timer:
    start_value: 3
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: goblin_solid_timer_start
        action: restart
      - event: goblin_solid_timer_stop
        action: stop

  goblin_hold_timer:
    start_value: 10
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: goblin_hold_timer_start
        action: restart
      - event: goblin_hold_timer_stop
        action: stop

show_player:
  mode_goblin_started:
    goblin_mode_start_show:
      loops: 0

  goblin_lite_left_web:
    goblin_left_web_flash_show:
      loops: -1
  goblin_lite_right_web:
    goblin_right_web_flash_show:
      loops: -1
  goblin_lite_spinner:
    goblin_spinner_flash_show:
      loops: -1
  goblin_lite_left_drops:
    goblin_left_drops_flash_show:
      loops: -1
  goblin_lite_right_drops:
    goblin_right_drops_flash_show:
      loops: -1
  goblin_lite_upper_spinner:
    goblin_upper_spinner_flash_show:
      loops: -1
  goblin_lite_saucers:
    goblin_saucers_flash_show:
      loops: -1
  goblin_lite_upper_target:
    goblin_upper_target_flash_show:
      loops: -1

  goblin_solid_left_web:
    goblin_left_web_solid_show:
      loops: -1
  goblin_solid_right_web:
    goblin_right_web_solid_show:
      loops: -1
  goblin_solid_spinner:
    goblin_spinner_solid_show:
      loops: -1
  goblin_solid_left_drops:
    goblin_left_drops_solid_show:
      loops: -1
  goblin_solid_right_drops:
    goblin_right_drops_solid_show:
      loops: -1
  goblin_solid_upper_spinner:
    goblin_upper_spinner_solid_show:
      loops: -1
  goblin_solid_saucers:
    goblin_saucers_solid_show:
      loops: -1
  goblin_solid_upper_target:
    goblin_upper_target_solid_show:
      loops: -1

  goblin_stop_left_web:
    goblin_left_web_flash_show:
      action: stop
    goblin_left_web_solid_show:
      action: stop

  goblin_stop_right_web:
    goblin_right_web_flash_show:
      action: stop
    goblin_right_web_solid_show:
      action: stop

  goblin_stop_spinner:
    goblin_spinner_flash_show:
      action: stop
    goblin_spinner_solid_show:
      action: stop

  goblin_stop_left_drops:
    goblin_left_drops_flash_show:
      action: stop
    goblin_left_drops_solid_show:
      action: stop

  goblin_stop_right_drops:
    goblin_right_drops_flash_show:
      action: stop
    goblin_right_drops_solid_show:
      action: stop

  goblin_stop_upper_spinner:
    goblin_upper_spinner_flash_show:
      action: stop
    goblin_upper_spinner_solid_show:
      action: stop

  goblin_stop_saucers:
    goblin_saucers_flash_show:
      action: stop
    goblin_saucers_solid_show:
      action: stop

  goblin_stop_upper_target:
    goblin_upper_target_flash_show:
      action: stop
    goblin_upper_target_solid_show:
      action: stop

  goblin_stop_all_shows:
    goblin_left_web_flash_show:
      action: stop
    goblin_right_web_flash_show:
      action: stop
    goblin_spinner_flash_show:
      action: stop
    goblin_left_drops_flash_show:
      action: stop
    goblin_right_drops_flash_show:
      action: stop
    goblin_upper_spinner_flash_show:
      action: stop
    goblin_saucers_flash_show:
      action: stop
    goblin_upper_target_flash_show:
      action: stop
    goblin_left_web_solid_show:
      action: stop
    goblin_right_web_solid_show:
      action: stop
    goblin_spinner_solid_show:
      action: stop
    goblin_left_drops_solid_show:
      action: stop
    goblin_right_drops_solid_show:
      action: stop
    goblin_upper_spinner_solid_show:
      action: stop
    goblin_saucers_solid_show:
      action: stop
    goblin_upper_target_solid_show:
      action: stop


shows:

  goblin_left_web_flash_show:
    - duration: 120ms
      lights:
        l_left_web_target: yellow
    - duration: 120ms
      lights:
        l_left_web_target: green

  goblin_right_web_flash_show:
    - duration: 120ms
      lights:
        l_mid_spider_target: yellow
    - duration: 120ms
      lights:
        l_mid_spider_target: green

  goblin_spinner_flash_show:
    - duration: 120ms
      lights:
        l_spinner: yellow
    - duration: 120ms
      lights:
        l_spinner: green

  goblin_left_drops_flash_show:
    - duration: 120ms
      lights:
        l_3bankbonus: yellow
        l_extraball: yellow
    - duration: 120ms
      lights:
        l_3bankbonus: green
        l_extraball: green

  goblin_right_drops_flash_show:
    - duration: 120ms
      lights:
        l_5bank_1: yellow
        l_5bank_2: yellow
        l_5bank_3: yellow
        l_5bank_4: yellow
        l_5bank_5: yellow
    - duration: 120ms
      lights:
        l_5bank_1: green
        l_5bank_2: green
        l_5bank_3: green
        l_5bank_4: green
        l_5bank_5: green

  goblin_upper_spinner_flash_show:
    - duration: 120ms
      lights:
        l_gi_a: yellow
    - duration: 120ms
      lights:
        l_gi_a: green

  goblin_saucers_flash_show:
    - duration: 120ms
      lights:
        l_1_hole_l: yellow
        l_1: yellow
        l_1_hole_r: yellow
        l_2_hole_l: yellow
        l_2: yellow
        l_2_hole_r: yellow
        l_3_hole_l: yellow
        l_3: yellow
        l_3_hole_r: yellow
    - duration: 120ms
      lights:
        l_1_hole_l: green
        l_1: green
        l_1_hole_r: green
        l_2_hole_l: green
        l_2: green
        l_2_hole_r: green
        l_3_hole_l: green
        l_3: green
        l_3_hole_r: green

  goblin_upper_target_flash_show:
    - duration: 120ms
      lights:
        l_upper_left: yellow
        l_upper_middle: yellow
        l_upper_right: yellow
    - duration: 120ms
      lights:
        l_upper_left: green
        l_upper_middle: green
        l_upper_right: green

  goblin_left_web_solid_show:
    - duration: -1
      lights:
        l_left_web_target: green

  goblin_right_web_solid_show:
    - duration: -1
      lights:
        l_mid_spider_target: green

  goblin_spinner_solid_show:
    - duration: -1
      lights:
        l_spinner: green

  goblin_left_drops_solid_show:
    - duration: -1
      lights:
        l_3bankbonus: green
        l_extraball: green

  goblin_right_drops_solid_show:
    - duration: -1
      lights:
        l_5bank_1: green
        l_5bank_2: green
        l_5bank_3: green
        l_5bank_4: green
        l_5bank_5: green

  goblin_upper_spinner_solid_show:
    - duration: -1
      lights:
        l_gi_a: green

  goblin_saucers_solid_show:
    - duration: -1
      lights:
        l_1_hole_l: green
        l_1: green
        l_1_hole_r: green
        l_2_hole_l: green
        l_2: green
        l_2_hole_r: green
        l_3_hole_l: green
        l_3: green
        l_3_hole_r: green

  goblin_upper_target_solid_show:
    - duration: -1
      lights:
        l_upper_left: green
        l_upper_middle: green
        l_upper_right: green        

  goblin_mode_start_show:
    - duration: -1
      lights:
        gi: green