#config_version=6
hardware:
    platform: fast 
fast:
  net:
    controller: neuron
    io_loop:
      cab:
        model: FP-I/O-0024
        order: 1
      3208:
        model: FP-I/O-3208
        order: 2
      1616mid:
        model: FP-I/O-1616
        order: 3
      1616bot:
        model: FP-I/O-1616
        order: 4
    port: auto
    baud: 921600
    debug: false
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms
  exp:
    boards:
      playfield:
        model: FP-EXP-0071
        led_fade_time: 100ms
    port: auto
    baud: 921600
    debug: False

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
  - s_trough5
  - s_trough6




#Game Config
config:
  - lights.yaml
  - coils.yaml
  - switches.yaml
  - devices.yaml
  - player_vars.yaml
  #- sounds.yaml
  - images.yaml
  - videos.yaml

playfields:
  playfield:    
    default_source_device: bd_plunger
    tags: default

machine:
  balls_installed: 6

game:
  balls_per_game: 3
  max_players: 4



modes:
  - attract
  - base
  - music_control
  - service
  - high_score
  - tilt
  - bonus
  - bonus_lanes
  - daily_bugle_mystery
  - extra_ball
  - skillshot
  - custom_bonus
  - super_spinner
  - super_pops
  - chaos_pops
  - villain_bookends
  - rhino
  - sandman
  - vulture
  - lizard
  - electro
  - goblin
  - doc_ock
  - mysterio
  - scorpion
  - parafino
  - cerberus
  - vulcan
  - diana
  - cyclops
  - centaur
  - kingpin
  - human_flies
  - fifth_avenue_phantom
  - enforcers
  - diamond_smugglers
  - pardo
  - fakir
  - scarlet_sorcerer
  - super_swami
  - frog_ghosts
  - noah_boddy
  - dr_magneto
  - professor_pretoris
  - doctor_dumpty
  - dr_von_schlick
  - radiation_specialist
  - dr_zap
  - doctor_cool
  - snowman
  - ice_monster
  - dr_manta
  - doctor_atlantean
  - sky_master
  - plutonians
  - antarcticans
  - charles_cameo
  - brutus
  - eigor
  - the_fly
  - swamp_reptiles
  - phantom_from_depths_of_time
  - master_vine
  - master_technician
  - micro_men
  - grand_emperor
  - sinister_surge
  - mastermind_trap
  - trubble_unleashed
  - master_plan
  - fifth_dimension_curse
  - mad_science_meltdown
  - nature_strikes_back
  - invasion_from_everywhere
  - who_is_the_real_villain
  - time_tossed_showdown
  - final_showdown
  - daily_bugle_rooftop_riot
  - qualify_system
  - villain_select
  - villain_start
  - case_files
  - villain_progression

event_player:
  ball_starting:
    - cmd_flippers_enable
    - cmd_autofire_coils_enable
    - cmd_drop_targets_reset
  ball_ending:
    - cmd_flippers_disable
    - cmd_autofire_coils_disable
    - timer_timer_up_post_hold_complete
  tilt:
    - cmd_flippers_disable
    - cmd_autofire_coils_disable
    - timer_timer_up_post_hold_complete
    - case_files_clear_lights
    - clear_villain_saucer_lights
    - reset_drops
    - clear_saucers

  slam_tilt:
    - cmd_flippers_disable
    - cmd_autofire_coils_disable
    - timer_timer_up_post_hold_complete
    - case_files_clear_lights
    - clear_villain_saucer_lights
    - reset_drops
    - clear_saucers
    
  rooftop_diverter_open{device.switches.s_diverter_open.state == 1}:
    - fire_rooftop_diverter_open
    
  rooftop_diverter_close{device.switches.s_diverter_open.state == 0}:
    - fire_rooftop_diverter_close

  s_plunger_active{current_player.multiball_autoplunge_active == 1}:
    - plunger_auto_fire|2s

  ball_started{current_player.multiball_autoplunge_active == 1}:
    - disable_outlane_autoplunge

  drop_target_bank_dt_bank_left_down{current_player.villain_mode_running == 0}:
    - drop_target_bank_dt_bank_left_reset

  drop_target_bank_dt_bank_right_down{current_player.villain_mode_running == 0}:
    - drop_target_bank_dt_bank_right_reset

  reset_drops:
    - reset_3bank
    - reset_5bank|300ms

  villain_full_cleanup:
    - case_files_clear_lights
    - case_files_reset_all
    - clear_villain_saucer_lights
    - clear_saucers
    - reset_drops

  reset_5bank_delayed:
    - reset_5bank|500ms



extra_ball_groups:
  main_extra_ball_group:
    max_per_game: 3
    light_events: mystery_extra_ball_lit
    award_lit_events: mystery_extra_ball_award


coil_player:
  enable_up_post_event:
    c_up_post:
      action: enable    
      
  timer_timer_up_post_hold_complete:
    c_up_post:
      action: disable

  mode_base_stopping:
    c_up_post:
      action: disable

  kickout_saucer_1:
    c_saucer_1:
      action: pulse

  kickout_saucer_2:
    c_saucer_2:
      action: pulse

  kickout_saucer_3:
    c_saucer_3:
      action: pulse

  up_kick:
    c_vuk_to_upper:
      action: pulse
    
  fire_rooftop_diverter_open:
    c_diverter_open_close:
      action: pulse
      pulse_ms: 220
  
  fire_rooftop_diverter_close:
    c_diverter_open_close:
      action: pulse
      pulse_ms: 100    

  reset_5bank:
    c_right_bank_reset:
      action: pulse

  reset_3bank:
    c_left_bank_reset:
      action: pulse

  plunger_auto_fire:
    c_auto_plunger:
      action: pulse
      

sound_player:
  up_kick:
    hb_spring_1:
      action: play
      bus: effects

 
sequences:
  reset_left_bank_after_hit:
    events:
      - drop_target_bank_dt_bank_left_down
      - xxxs_web_target_left_active
    reset_on_complete: true
    disable_on_complete: false
    events_when_complete: drop_target_bank_dt_bank_left_reset
  
  reset_right_bank_after_hit:
    events:
      - drop_target_bank_dt_bank_right_down
      - xxxs_web_target_mid_active
    reset_on_complete: true
    disable_on_complete: false
    events_when_complete: drop_target_bank_dt_bank_right_reset



ball_saves:

  mystery_ball_save:
    active_time: 10s
    hurry_up_time: 3s
    grace_period: 2s
    enable_events:
      - mystery_award_ball_save


  default_ball_save:
    active_time: 16s
    hurry_up_time: 3s
    grace_period: 2s
    enable_events:
      - start_my_default_ball_save
#    timer_start_events:
#      - playfield_active      


  case_file_ball_save:
    active_time: 10s
    hurry_up_time: 3s
    grace_period: 2s
    enable_events:
      - start_case_file_ball_save





#todo - when ball saved, use these events to trigger display
#ball_save_default_ball_save_saving_ball
#  - start ball save show (flash light) and video
#ball_save_default_ball_save_enabled
#ball_save_default_ball_save_hurry_up
#  - blink light faster
#ball_save_default_ball_save_disabled
#  - turn off light
#ball_save_default_ball_save_timer_start
# event_player:

#  ball_save_default_ball_save_saving_ball:
#    - play_ball_save_callout
#    - flash_gi_blue


