#config_version=6

mode:
  start_events: start_mode_doctor_dumpty
  stop_events:
    - ball_will_end
    - bonus_start
    - doctor_dumpty_mode_complete
    - doctor_dumpty_mode_completed_summary
    - ball_ended
  code: doctor_dumpty.DoctorDumpty
  priority: 300

widget_player:
  mode_doctor_dumpty_started:
    doctor_dumpty:
      action: play
  doctor_dumpty_mode_complete:
    doctor_dumpty:
      action: remove
  mode_doctor_dumpty_stopping:
    doctor_dumpty:
      action: remove

event_player:
  doctor_dumpty_startup_complete:
    - clear_saucers
    - reset_drops

  s_left_drops_1_active: doctor_dumpty_left_drop_1
  s_left_drops_2_active: doctor_dumpty_left_drop_2
  s_left_drops_3_active: doctor_dumpty_left_drop_3

  s_sling_l_active: doctor_dumpty_gas_left_sling
  s_sling_r_active: doctor_dumpty_gas_right_sling
  s_pop_left_active: doctor_dumpty_gas_left_pop
  s_pop_right_active: doctor_dumpty_gas_right_pop
  s_right_drops_1_active: doctor_dumpty_gas_right_bank
  s_right_drops_2_active: doctor_dumpty_gas_right_bank
  s_right_drops_3_active: doctor_dumpty_gas_right_bank
  s_right_drops_4_active: doctor_dumpty_gas_right_bank
  s_right_drops_5_active: doctor_dumpty_gas_right_bank

  s_upper_entrance_opto_active: doctor_dumpty_upper_entry
  s_upper_target_left_active: doctor_dumpty_upper_target_hit
  s_upper_target_center_active: doctor_dumpty_upper_target_hit
  s_upper_target_right_active: doctor_dumpty_upper_target_hit
  s_trispinner_opto_active: doctor_dumpty_upper_spinner_hit

  s_vuk_switch_active:
    - request_vuk_eject

  s_saucer_1_active: clear_saucers
  s_saucer_2_active: clear_saucers
  s_saucer_3_active: clear_saucers

  drop_target_bank_dt_bank_right_down:
    - drop_target_bank_dt_bank_right_reset

sound_player:
  play_mode_jackpot:
    jackpot_2:
      action: play
      bus: effects
  play_mode_super_jackpot:
    jackpot_2:
      action: play
      bus: effects

  doctor_dumpty_balloon_popped:
    popping:
      action: play
      bus: effects

show_player:
  doctor_dumpty_gas_phase_started:
    doctor_dumpty_left_bank_blue:
      loops: -1
  doctor_dumpty_gas_phase_complete:
    doctor_dumpty_left_bank_blue:
      action: stop

  doctor_dumpty_light_gas_left_sling:
    doctor_dumpty_gas_left_sling:
      loops: -1
  doctor_dumpty_stop_gas_left_sling:
    doctor_dumpty_gas_left_sling:
      action: stop
  doctor_dumpty_light_gas_right_sling:
    doctor_dumpty_gas_right_sling:
      loops: -1
  doctor_dumpty_stop_gas_right_sling:
    doctor_dumpty_gas_right_sling:
      action: stop
  doctor_dumpty_light_gas_left_pop:
    doctor_dumpty_gas_left_pop:
      loops: -1
  doctor_dumpty_stop_gas_left_pop:
    doctor_dumpty_gas_left_pop:
      action: stop
  doctor_dumpty_light_gas_right_pop:
    doctor_dumpty_gas_right_pop:
      loops: -1
  doctor_dumpty_stop_gas_right_pop:
    doctor_dumpty_gas_right_pop:
      action: stop
  doctor_dumpty_light_gas_right_bank:
    doctor_dumpty_gas_right_bank:
      loops: -1
  doctor_dumpty_stop_gas_right_bank:
    doctor_dumpty_gas_right_bank:
      action: stop

  doctor_dumpty_roof_phase_started:
    doctor_dumpty_upper_red:
      loops: -1

  doctor_dumpty_all_lights_off:
    doctor_dumpty_left_bank_blue:
      action: stop
    doctor_dumpty_gas_left_sling:
      action: stop
    doctor_dumpty_gas_right_sling:
      action: stop
    doctor_dumpty_gas_left_pop:
      action: stop
    doctor_dumpty_gas_right_pop:
      action: stop
    doctor_dumpty_gas_right_bank:
      action: stop
    doctor_dumpty_upper_red:
      action: stop

shows:
  doctor_dumpty_left_bank_blue:
    - duration: 500ms
      lights:
        l_gi_3bank: blue

  doctor_dumpty_gas_left_sling:
    - duration: 300ms
      lights:
        l_gi_left_sling_upper: green
        l_gi_left_sling_lower: green
    - duration: 300ms
      lights:
        l_gi_left_sling_upper: off
        l_gi_left_sling_lower: off

  doctor_dumpty_gas_right_sling:
    - duration: 300ms
      lights:
        l_gi_right_sling: green
    - duration: 300ms
      lights:
        l_gi_right_sling: off

  doctor_dumpty_gas_left_pop:
    - duration: 300ms
      lights:
        l_pop_1_1: green
        l_pop_1_2: green
        l_pop_1_3: green
        l_pop_1_4: green
        l_pop_1_5: green
        l_pop_1_6: green
        l_pop_1_7: green
        l_pop_1_8: green
        l_pop_1_9: green
        l_pop_1_10: green
        l_pop_1_11: green
        l_pop_1_12: green
    - duration: 300ms
      lights:
        l_pop_1_1: off
        l_pop_1_2: off
        l_pop_1_3: off
        l_pop_1_4: off
        l_pop_1_5: off
        l_pop_1_6: off
        l_pop_1_7: off
        l_pop_1_8: off
        l_pop_1_9: off
        l_pop_1_10: off
        l_pop_1_11: off
        l_pop_1_12: off

  doctor_dumpty_gas_right_pop:
    - duration: 300ms
      lights:
        l_pop_2_1: green
        l_pop_2_2: green
        l_pop_2_3: green
        l_pop_2_4: green
        l_pop_2_5: green
        l_pop_2_6: green
        l_pop_2_7: green
        l_pop_2_8: green
        l_pop_2_9: green
        l_pop_2_10: green
        l_pop_2_11: green
        l_pop_2_12: green
    - duration: 300ms
      lights:
        l_pop_2_1: off
        l_pop_2_2: off
        l_pop_2_3: off
        l_pop_2_4: off
        l_pop_2_5: off
        l_pop_2_6: off
        l_pop_2_7: off
        l_pop_2_8: off
        l_pop_2_9: off
        l_pop_2_10: off
        l_pop_2_11: off
        l_pop_2_12: off

  doctor_dumpty_gas_right_bank:
    - duration: 300ms
      lights:
        l_gi_5bank_lower: green
        l_5bank_1: green
        l_5bank_2: green
        l_5bank_3: green
        l_5bank_4: green
        l_5bank_5: green
    - duration: 300ms
      lights:
        l_gi_5bank_lower: off
        l_5bank_1: off
        l_5bank_2: off
        l_5bank_3: off
        l_5bank_4: off
        l_5bank_5: off

  doctor_dumpty_upper_red:
    - duration: 250ms
      lights:
        l_upper_left: red
        l_upper_middle: red
        l_upper_right: red
    - duration: 250ms
      lights:
        l_upper_left: off
        l_upper_middle: off
        l_upper_right: off
