#config_version=6

mode:
  start_events: start_mode_villain_select
  stop_events: stop_carousel_select
  code: qualify_villain_select.QualifyVillainSelect
  priority: 500

mode_settings:
  selectable_items:
    - lizard
    - rhino
    - sandman
    - vulture
    - electro
    - goblin
    - mysterio
    - scorpion
    - doc_ock
    - parafino

  next_item_events: villain_carousel_next
  previous_item_events: villain_carousel_previous
  select_item_events: villain_carousel_accept_selection


event_player:
  s_right_flipper_inactive{device.switches.s_left_flipper.state == 0}:
    villain_carousel_next

  s_left_flipper_inactive{device.switches.s_right_flipper.state == 0}:
    villain_carousel_previous




slide_player:
  mode_qualify_villain_select_started:
    villain_select:
      priority: 1000
      action: play

  stop_carousel_select:
    villain_select:
      action: remove

