#config_version=6

mode:
  start_events: start_mode_villain_select
  stop_events: stop_carousel_select
  code: qualify_villain_select.QualifyVillainSelect
  priority: 500

mode_settings:
  selectable_items:
    - lizard
    - rhino
    - sandman
    - vulture
    - electro
    - goblin
    - mysterio
    - scorpion
    - doc_ock
    - parafino

  next_item_events: s_right_flipper_inactive
  previous_item_events: s_left_flipper_inactive
  select_item_events: both_flippers_pressed_within_1s
  block_events: carousel_selection_locked
  release_events: carousel_selection_unlocked

timed_switches:
  both_flippers_held:
    switch_tags: left_flipper, right_flipper
    time: 1s
    events_when_active: both_flippers_pressed_within_1s
    events_when_released: both_flippers_inactive
