#config_version=6

# Sinister Surge placeholder mini-wizard.
# Classic Rogues mini-wizard. 2-ball MB. Rhino=Pops, Vulture=Rooftop spinner, Lizard=Star/Web, Sandman=Drops, Electro=Moving spark. Complete all five villain shots to light Daily Bugle Jackpot.

mode:
  start_events: start_mode_sinister_surge
  stop_events:
    - stop_mode_sinister_surge
    - ball_ended
  code: sinister_surge.SinisterSurge
  priority: 800

multiballs:
  sinister_surge_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 15s
    start_events: sinister_surge_start_multiball
    stop_events:
      - stop_mode_sinister_surge


widget_player:
  mode_sinister_surge_started:
    sinister_surge:
      action: play

  sinister_surge_mode_complete:
    sinister_surge:
      action: remove

  sinister_surge_mode_failed:
    sinister_surge:
      action: remove

  mode_sinister_surge_stopping:
    sinister_surge:
      action: remove

  stop_mode_sinister_surge:
    sinister_surge:
      action: remove

event_player:
  s_pop_left_active: sinister_surge_shot_hit
  s_pop_right_active: sinister_surge_shot_hit
  s_trispinner_opto_active: sinister_surge_shot_hit
  s_web_spinner_active: sinister_surge_shot_hit
  s_star_rollover_active: sinister_surge_shot_hit
  s_upper_target_left_active: sinister_surge_shot_hit
  s_upper_target_center_active: sinister_surge_shot_hit
  s_upper_target_right_active: sinister_surge_shot_hit
  s_left_drops_1_active: sinister_surge_shot_hit
  s_left_drops_2_active: sinister_surge_shot_hit
  s_left_drops_3_active: sinister_surge_shot_hit
  s_right_drops_1_active: sinister_surge_shot_hit
  s_right_drops_2_active: sinister_surge_shot_hit
  s_right_drops_3_active: sinister_surge_shot_hit
  s_right_drops_4_active: sinister_surge_shot_hit
  s_right_drops_5_active: sinister_surge_shot_hit

  s_vuk_switch_active: sinister_surge_jackpot_hit

  multiball_sinister_surge_multiball_ended: sinister_surge_failed

  mode_sinister_surge_started:
    - clear_saucers
    - drop_target_bank_dt_bank_left_reset
    - drop_target_bank_dt_bank_right_reset

  mode_sinister_surge_stopping:
    - clear_saucers
