#config_version=6

mode:
  start_events: ball_started
  priority: 100




sound_player:
  play_song_1: 
    prowl_car:
      bus: music

  play_song_2: 
    panic_patrol:
      bus: music
      
  play_song_3: 
    rat_race:
      bus: music
#loop?
