#config_version=6

mode:
  start_events: ball_started
  priority: 100
  code: music_control.MusicControl

sound_player:
  play_music_song_1: 
    prowl_car:
      bus: music
      loops: -1

  play_music_song_2: 
    panic_patrol:
      bus: music
      loops: -1

  play_music_song_3: 
    rat_race:
      bus: music
      loops: -1

  play_music_song_4: 
    ticking:
      bus: music
      loops: -1

  play_music_song_5: 
    start_loop:
      bus: music
      loops: -1

  play_music_song_6: 
    maintheme_no_lyrics:
      bus: music
      loops: -1

  play_music_song_7: 
    dash_to_safety:
      bus: music
      loops: -1

  play_music_song_8: 
    cloak:
      bus: music
      loops: -1

  play_music_song_9: 
    fright:
      bus: music
      loops: -1

  play_music_song_10: 
    fromthebird:
      bus: music
      loops: -1

  play_music_song_11: 
    intro_loop_2:
      bus: music
      loops: -1

  play_music_song_12: 
    intro_mild:
      bus: music
      loops: -1

  play_music_song_13: 
    loopy1:
      bus: music
      loops: -1

  play_music_song_14: 
    loopystart:
      bus: music
      loops: -1

  play_music_song_15: 
    loop_123:
      bus: music
      loops: -1

  play_music_song_16: 
    loop_123456:
      bus: music
      loops: -1

  play_music_song_17: 
    maintheme:
      bus: music
      loops: -1

  play_music_song_18: 
    paroxism:
      bus: music
      loops: -1

  play_music_song_19: 
    shakeandstone:
      bus: music
      loops: -1

  play_music_song_20: 
    somethings_up:
      bus: music
      loops: -1

  play_music_song_21: 
    spider_intro_strong:
      bus: music
      loops: -1

  play_music_song_22: 
    street_beat:
      bus: music
      loops: -1

  play_music_song_23: 
    tautwalk:
      bus: music
      loops: -1

  play_music_song_24: 
    twilight_guitar:
      bus: music
      loops: -1

  play_music_song_25: 
    waiting:
      bus: music
      loops: -1

  play_music_song_26: 
    intro_mild:
      bus: music
      loops: -1

  play_music_song_27: 
    dash_to_safety_2:
      bus: music
      loops: -1

  play_music_song_28: 
    dash_to_safety_3:
      bus: music
      loops: -1

  play_music_song_29:
    anji:
      bus: music
      loops: -1

  play_music_song_30:
    besame_mucho:
      bus: music
      loops: -1

  play_music_song_31:
    blood_and_black_lace:
      bus: music
      loops: -1

  play_music_song_32:
    danube_incident:
      bus: music
      loops: -1

  play_music_song_33:
    happy_go_lively:
      bus: music
      loops: -1

  play_music_song_34:
    la_buritta:
      bus: music
      loops: -1

  play_music_song_35:
    spooky:
      bus: music
      loops: -1

  play_music_song_36:
    sunflower:
      bus: music
      loops: -1

  play_music_song_37:
    the_enchanted_sea:
      bus: music
      loops: -1

  play_music_song_38:
    the_hearse:
      bus: music
      loops: -1

  play_music_song_39:
    the_ox:
      bus: music
      loops: -1

  play_music_song_40:
    yegelle_tezeta:
      bus: music
      loops: -1

  play_music_song_41:
    action_line:
      bus: music
      loops: -1

