#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ending
  priority: 10000
  code: villain_bookends.VillainBookends

event_player:
  flipper_cradle{current_player.villain_mode_running == 1}:
    - villain_bookend_intro_hold_request

  flipper_cradle_release:
    - villain_bookend_intro_hold_release

  villain_mode_ended:  #todo - generate this on mode ends?
    - villain_bookend_intro_hold_release


random_event_player:
  villain_bookend_summary_done:
    - play_song_1
    - play_song_2
    - play_song_3

widget_player:
  villain_bookend_intro_show:
    villain_intro:
      action: play

  villain_bookend_intro_hide:
    villain_intro:
      action: remove

  villain_bookend_summary_show:
    villain_summary:
      action: play

  villain_bookend_summary_hide:
    villain_summary:
      action: remove