#config_version=6

mode:
  start_events: start_mode_molemen
  stop_events:
    - molemen_mode_complete
    - molemen_mode_completed_summary
    - ball_ended
  code: molemen.Molemen
  priority: 800

multiballs:
  molemen_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: (current_player.molemen_opening_save_seconds)
    start_events: molemen_start_multiball
    add_a_ball_events:
      - molemen_add_a_ball
    add_a_ball_shoot_again: (current_player.molemen_add_a_ball_save_seconds)
    add_a_ball_hurry_up_time: 3s

variable_player:
  multiball_molemen_multiball_started:
    multiball_autoplunge_active:
      action: set
      int: 1
  multiball_molemen_multiball_ended:
    multiball_autoplunge_active:
      action: set
      int: 0

event_player:
  molemen_startup_complete:
    - clear_saucers_delayed
    - reset_drops
    - rooftop_diverter_close
    - molemen_light_area_zones
    - molemen_start_multiball|1s

  drop_target_bank_dt_bank_left_down:
    - drop_target_bank_dt_bank_left_reset

  drop_target_bank_dt_bank_right_down:
    - drop_target_bank_dt_bank_right_reset

  mode_molemen_stopping:
    - molemen_clear_all_lights
    - clear_saucers_delayed
    - rooftop_diverter_close

widget_player:
  mode_molemen_started:
    molemen:
      action: play
  molemen_mode_completed_summary:
    molemen:
      action: remove
  mode_molemen_stopping:
    molemen:
      action: remove

show_player:
  molemen_clear_all_lights:
    molemen_left_area_show: {action: stop}
    molemen_center_area_show: {action: stop}
    molemen_right_area_show: {action: stop}
    molemen_saucer_1_jackpot_show: {action: stop}
    molemen_saucer_2_jackpot_show: {action: stop}
    molemen_saucer_3_jackpot_show: {action: stop}
    molemen_saucer_1_add_ball_show: {action: stop}
    molemen_saucer_2_add_ball_show: {action: stop}
    molemen_saucer_3_add_ball_show: {action: stop}

  molemen_light_area_zones:
    molemen_left_area_show: {action: play, loops: -1}
    molemen_center_area_show: {action: play, loops: -1}
    molemen_right_area_show: {action: play, loops: -1}

  molemen_saucer_1_jackpot_lit:
    molemen_saucer_1_jackpot_show: {action: play, loops: -1}
  molemen_saucer_2_jackpot_lit:
    molemen_saucer_2_jackpot_show: {action: play, loops: -1}
  molemen_saucer_3_jackpot_lit:
    molemen_saucer_3_jackpot_show: {action: play, loops: -1}

  molemen_saucer_1_add_ball_ready:
    molemen_saucer_1_add_ball_show: {action: play, loops: -1}
  molemen_saucer_2_add_ball_ready:
    molemen_saucer_2_add_ball_show: {action: play, loops: -1}
  molemen_saucer_3_add_ball_ready:
    molemen_saucer_3_add_ball_show: {action: play, loops: -1}

  molemen_saucer_1_reset:
    molemen_saucer_1_jackpot_show: {action: stop}
    molemen_saucer_1_add_ball_show: {action: stop}
  molemen_saucer_2_reset:
    molemen_saucer_2_jackpot_show: {action: stop}
    molemen_saucer_2_add_ball_show: {action: stop}
  molemen_saucer_3_reset:
    molemen_saucer_3_jackpot_show: {action: stop}
    molemen_saucer_3_add_ball_show: {action: stop}

shows:
  molemen_left_area_show:
    - duration: 500ms
      lights:
        l_pop_1_1: white
        l_pop_1_2: white
        l_pop_1_3: white
        l_pop_1_4: white
        l_pop_1_5: white
        l_pop_1_6: white
        l_pop_1_7: white
        l_pop_1_8: white
        l_pop_1_9: white
        l_pop_1_10: white
        l_pop_1_11: white
        l_pop_1_12: white
    - duration: 500ms
      lights:
        l_pop_1_1: off
        l_pop_1_2: off
        l_pop_1_3: off
        l_pop_1_4: off
        l_pop_1_5: off
        l_pop_1_6: off
        l_pop_1_7: off
        l_pop_1_8: off
        l_pop_1_9: off
        l_pop_1_10: off
        l_pop_1_11: off
        l_pop_1_12: off

  molemen_center_area_show:
    - duration: 500ms
      lights:
        l_mid_web_target: white
    - duration: 500ms
      lights:
        l_mid_web_target: off

  molemen_right_area_show:
    - duration: 500ms
      lights:
        l_pop_2_1: white
        l_pop_2_2: white
        l_pop_2_3: white
        l_pop_2_4: white
        l_pop_2_5: white
        l_pop_2_6: white
        l_pop_2_7: white
        l_pop_2_8: white
        l_pop_2_9: white
        l_pop_2_10: white
        l_pop_2_11: white
        l_pop_2_12: white
    - duration: 500ms
      lights:
        l_pop_2_1: off
        l_pop_2_2: off
        l_pop_2_3: off
        l_pop_2_4: off
        l_pop_2_5: off
        l_pop_2_6: off
        l_pop_2_7: off
        l_pop_2_8: off
        l_pop_2_9: off
        l_pop_2_10: off
        l_pop_2_11: off
        l_pop_2_12: off

  molemen_saucer_1_jackpot_show:
    - duration: 500ms
      lights: {l_1_hole_l: red, l_1_hole_r: red}
    - duration: 500ms
      lights: {l_1_hole_l: off, l_1_hole_r: off}
  molemen_saucer_2_jackpot_show:
    - duration: 500ms
      lights: {l_2_hole_l: red, l_2_hole_r: red}
    - duration: 500ms
      lights: {l_2_hole_l: off, l_2_hole_r: off}
  molemen_saucer_3_jackpot_show:
    - duration: 500ms
      lights: {l_3_hole_l: red, l_3_hole_r: red}
    - duration: 500ms
      lights: {l_3_hole_l: off, l_3_hole_r: off}

  molemen_saucer_1_add_ball_show:
    - duration: 250ms
      lights: {l_1: green, l_1_hole_l: red, l_1_hole_r: red}
    - duration: 250ms
      lights: {l_1: green, l_1_hole_l: off, l_1_hole_r: off}
  molemen_saucer_2_add_ball_show:
    - duration: 250ms
      lights: {l_2: green, l_2_hole_l: red, l_2_hole_r: red}
    - duration: 250ms
      lights: {l_2: green, l_2_hole_l: off, l_2_hole_r: off}
  molemen_saucer_3_add_ball_show:
    - duration: 250ms
      lights: {l_3: green, l_3_hole_l: red, l_3_hole_r: red}
    - duration: 250ms
      lights: {l_3: green, l_3_hole_l: off, l_3_hole_r: off}

light_player:
  mode_molemen_started:
    gi: C8F0FF
  mode_molemen_stopping:
    gi: E0E0E0
