#config_version=6

mode:
  start_events: start_mode_molemen
  stop_events:
    - molemen_mode_complete
    - molemen_mode_completed_summary
    - ball_ended
  code: molemen.Molemen
  priority: 800

multiballs:
  molemen_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: (current_player.molemen_opening_save_seconds)
    start_events: molemen_start_multiball
    add_a_ball_events:
      - molemen_add_a_ball
    add_a_ball_shoot_again: (current_player.molemen_add_a_ball_save_seconds)
    add_a_ball_hurry_up_time: 3s

variable_player:
  multiball_molemen_multiball_started:
    multiball_autoplunge_active:
      action: set
      int: 1
  multiball_molemen_multiball_ended:
    multiball_autoplunge_active:
      action: set
      int: 0

event_player:
  molemen_startup_complete:
    - clear_saucers_delayed
    - rooftop_diverter_close
    - molemen_start_multiball|1s

  mode_molemen_stopping:
    - molemen_clear_all_lights
    - clear_saucers_delayed
    - rooftop_diverter_close

widget_player:
  mode_molemen_started:
    molemen:
      action: play
  molemen_mode_completed_summary:
    molemen:
      action: remove
  mode_molemen_stopping:
    molemen:
      action: remove

show_player:
  molemen_clear_all_lights:
    molemen_saucer_1_jackpot_show: {action: stop}
    molemen_saucer_2_jackpot_show: {action: stop}
    molemen_saucer_3_jackpot_show: {action: stop}
    molemen_saucer_1_add_ball_show: {action: stop}
    molemen_saucer_2_add_ball_show: {action: stop}
    molemen_saucer_3_add_ball_show: {action: stop}

  molemen_saucer_1_jackpot_lit:
    molemen_saucer_1_jackpot_show: {action: play, loops: -1}
  molemen_saucer_2_jackpot_lit:
    molemen_saucer_2_jackpot_show: {action: play, loops: -1}
  molemen_saucer_3_jackpot_lit:
    molemen_saucer_3_jackpot_show: {action: play, loops: -1}

  molemen_saucer_1_add_ball_ready:
    molemen_saucer_1_add_ball_show: {action: play, loops: -1}
  molemen_saucer_2_add_ball_ready:
    molemen_saucer_2_add_ball_show: {action: play, loops: -1}
  molemen_saucer_3_add_ball_ready:
    molemen_saucer_3_add_ball_show: {action: play, loops: -1}

  molemen_saucer_1_reset:
    molemen_saucer_1_jackpot_show: {action: stop}
    molemen_saucer_1_add_ball_show: {action: stop}
  molemen_saucer_2_reset:
    molemen_saucer_2_jackpot_show: {action: stop}
    molemen_saucer_2_add_ball_show: {action: stop}
  molemen_saucer_3_reset:
    molemen_saucer_3_jackpot_show: {action: stop}
    molemen_saucer_3_add_ball_show: {action: stop}

shows:
  molemen_saucer_1_jackpot_show:
    - duration: 500ms
      lights: {l_1_hole_l: red, l_1_hole_r: red}
    - duration: 500ms
      lights: {l_1_hole_l: off, l_1_hole_r: off}
  molemen_saucer_2_jackpot_show:
    - duration: 500ms
      lights: {l_2_hole_l: red, l_2_hole_r: red}
    - duration: 500ms
      lights: {l_2_hole_l: off, l_2_hole_r: off}
  molemen_saucer_3_jackpot_show:
    - duration: 500ms
      lights: {l_3_hole_l: red, l_3_hole_r: red}
    - duration: 500ms
      lights: {l_3_hole_l: off, l_3_hole_r: off}

  molemen_saucer_1_add_ball_show:
    - duration: 250ms
      lights: {l_1_hole_l: red, l_1_hole_r: red}
    - duration: 250ms
      lights: {l_1_hole_l: off, l_1_hole_r: off}
  molemen_saucer_2_add_ball_show:
    - duration: 250ms
      lights: {l_2_hole_l: red, l_2_hole_r: red}
    - duration: 250ms
      lights: {l_2_hole_l: off, l_2_hole_r: off}
  molemen_saucer_3_add_ball_show:
    - duration: 250ms
      lights: {l_3_hole_l: red, l_3_hole_r: red}
    - duration: 250ms
      lights: {l_3_hole_l: off, l_3_hole_r: off}

light_player:
  mode_molemen_started:
    gi: C8F0FF
  mode_molemen_stopping:
    gi: E0E0E0
