#config_version=6

mode:
  start_events: start_mode_spider_slayer
  stop_events:
    - spider_slayer_mode_complete
    - spider_slayer_mode_completed_summary
    - ball_ended
  code: spider_slayer.SpiderSlayer
  priority: 300

widget_player:
  mode_spider_slayer_started:
    spider_slayer:
      action: play
  spider_slayer_mode_complete:
    spider_slayer:
      action: remove
  mode_spider_slayer_stopping:
    spider_slayer:
      action: remove

event_player:
  s_web_target_left_active: spider_slayer_shot_left_web
  s_web_target_mid_active: spider_slayer_shot_center_web
  s_sling_l_active: spider_slayer_shot_left_sling
  s_sling_r_active: spider_slayer_shot_right_sling
  s_pop_left_active: spider_slayer_shot_left_pop
  s_pop_right_active: spider_slayer_shot_right_pop
  s_star_rollover_active: spider_slayer_shot_star

  s_left_drops_1_active: spider_slayer_shot_left_bank
  s_left_drops_2_active: spider_slayer_shot_left_bank
  s_left_drops_3_active: spider_slayer_shot_left_bank
  s_left_drops_rubber_active: spider_slayer_shot_left_bank
  s_left_drops_top_left_rubber_active: spider_slayer_shot_left_bank
  s_left_drops_top_right_rubber_active: spider_slayer_shot_left_bank

  s_right_drops_1_active: spider_slayer_shot_right_bank
  s_right_drops_2_active: spider_slayer_shot_right_bank
  s_right_drops_3_active: spider_slayer_shot_right_bank
  s_right_drops_4_active: spider_slayer_shot_right_bank
  s_right_drops_5_active: spider_slayer_shot_right_bank
  s_right_drops_rubber_active: spider_slayer_shot_right_bank
  s_right_drops_top_rubber_active: spider_slayer_shot_right_bank

  s_saucer_1_active:
    - spider_slayer_shot_saucer
    - delayed_kickout_saucer_1|750ms
  s_saucer_2_active:
    - spider_slayer_shot_saucer
    - delayed_kickout_saucer_2|750ms
  s_saucer_3_active:
    - spider_slayer_shot_saucer
    - delayed_kickout_saucer_3|750ms
  s_vuk_switch_active: spider_slayer_vuk_hit

  drop_target_bank_dt_bank_left_down: drop_target_bank_dt_bank_left_reset
  drop_target_bank_dt_bank_right_down: drop_target_bank_dt_bank_right_reset

  mode_spider_slayer_started:
    - reset_drops
    - clear_saucers_delayed
  mode_spider_slayer_stopping:
    - clear_saucers_delayed

ball_saves:
  spider_slayer_safety_net:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 1s
    enable_events: spider_slayer_enable_safety_net
    disable_events:
      - spider_slayer_disable_safety_net
      - mode_spider_slayer_stopping
    auto_launch: true
    balls_to_save: 1

show_player:
  spider_slayer_hunt_started:
    spider_slayer_build_gi:
      loops: -1

  spider_slayer_light_left_web:
    spider_slayer_left_web_pulse:
      loops: -1
  spider_slayer_light_center_web:
    spider_slayer_center_web_pulse:
      loops: -1
  spider_slayer_light_left_sling:
    spider_slayer_left_sling_pulse:
      loops: -1
  spider_slayer_light_right_sling:
    spider_slayer_right_sling_pulse:
      loops: -1
  spider_slayer_light_left_pop:
    spider_slayer_left_pop_pulse:
      loops: -1
  spider_slayer_light_right_pop:
    spider_slayer_right_pop_pulse:
      loops: -1
  spider_slayer_light_left_bank:
    spider_slayer_left_bank_pulse:
      loops: -1
  spider_slayer_light_right_bank:
    spider_slayer_right_bank_pulse:
      loops: -1
  spider_slayer_light_star:
    spider_slayer_star_pulse:
      loops: -1
  spider_slayer_light_saucer:
    spider_slayer_saucer_pulse:
      loops: -1

  spider_slayer_successful_hit:
    spider_slayer_hit_flash:
      loops: 1

  spider_slayer_hunt_complete:
    spider_slayer_build_gi:
      action: stop
    spider_slayer_hit_flash:
      loops: 1
    spider_slayer_jackpot_gi:
      loops: -1
    spider_slayer_vuk_flash:
      loops: -1

  spider_slayer_clear_hunt_shots:
    spider_slayer_left_web_pulse: {action: stop}
    spider_slayer_center_web_pulse: {action: stop}
    spider_slayer_left_sling_pulse: {action: stop}
    spider_slayer_right_sling_pulse: {action: stop}
    spider_slayer_left_pop_pulse: {action: stop}
    spider_slayer_right_pop_pulse: {action: stop}
    spider_slayer_left_bank_pulse: {action: stop}
    spider_slayer_right_bank_pulse: {action: stop}
    spider_slayer_star_pulse: {action: stop}
    spider_slayer_saucer_pulse: {action: stop}

  spider_slayer_clear_all:
    spider_slayer_build_gi: {action: stop}
    spider_slayer_jackpot_gi: {action: stop}
    spider_slayer_vuk_flash: {action: stop}
    spider_slayer_left_web_pulse: {action: stop}
    spider_slayer_center_web_pulse: {action: stop}
    spider_slayer_left_sling_pulse: {action: stop}
    spider_slayer_right_sling_pulse: {action: stop}
    spider_slayer_left_pop_pulse: {action: stop}
    spider_slayer_right_pop_pulse: {action: stop}
    spider_slayer_left_bank_pulse: {action: stop}
    spider_slayer_right_bank_pulse: {action: stop}
    spider_slayer_star_pulse: {action: stop}
    spider_slayer_saucer_pulse: {action: stop}

light_player:
  spider_slayer_clear_all:
    gi: stop
    l_left_web_target: stop
    l_mid_web_target: stop
    l_gi_left_sling_upper: stop
    l_gi_left_sling_lower: stop
    l_gi_right_sling: stop
    l_pop_1_1: stop
    l_pop_2_1: stop
    l_gi_3bank: stop
    l_gi_5bank_lower: stop
    l_gi_5bank_upper: stop
    l_star: stop
    l_1_hole_l: stop
    l_1_hole_r: stop
    l_gi_left_upper: stop

shows:
  spider_slayer_build_gi:
    - duration: 1s
      lights: {gi: 401010}
  spider_slayer_jackpot_gi:
    - duration: 1s
      lights: {gi: 104020}
  spider_slayer_hit_flash:
    - duration: 250ms
      lights: {gi: FF3030}
    - duration: 250ms
      lights: {gi: 401010}
  spider_slayer_left_web_pulse:
    - duration: 500ms
      lights: {l_left_web_target: FF2020}
    - duration: 500ms
      lights: {l_left_web_target: 401010}
  spider_slayer_center_web_pulse:
    - duration: 500ms
      lights: {l_mid_web_target: FF2020}
    - duration: 500ms
      lights: {l_mid_web_target: 401010}
  spider_slayer_left_sling_pulse:
    - duration: 500ms
      lights: {l_gi_left_sling_upper: FF2020, l_gi_left_sling_lower: FF2020}
    - duration: 500ms
      lights: {l_gi_left_sling_upper: 401010, l_gi_left_sling_lower: 401010}
  spider_slayer_right_sling_pulse:
    - duration: 500ms
      lights: {l_gi_right_sling: FF2020}
    - duration: 500ms
      lights: {l_gi_right_sling: 401010}
  spider_slayer_left_pop_pulse:
    - duration: 500ms
      lights: {l_pop_1_1: FF2020}
    - duration: 500ms
      lights: {l_pop_1_1: 401010}
  spider_slayer_right_pop_pulse:
    - duration: 500ms
      lights: {l_pop_2_1: FF2020}
    - duration: 500ms
      lights: {l_pop_2_1: 401010}
  spider_slayer_left_bank_pulse:
    - duration: 500ms
      lights: {l_gi_3bank: FF2020}
    - duration: 500ms
      lights: {l_gi_3bank: 401010}
  spider_slayer_right_bank_pulse:
    - duration: 500ms
      lights: {l_gi_5bank_lower: FF2020, l_gi_5bank_upper: FF2020}
    - duration: 500ms
      lights: {l_gi_5bank_lower: 401010, l_gi_5bank_upper: 401010}
  spider_slayer_star_pulse:
    - duration: 500ms
      lights: {l_star: FF2020}
    - duration: 500ms
      lights: {l_star: 401010}
  spider_slayer_saucer_pulse:
    - duration: 500ms
      lights: {l_1_hole_l: FF2020, l_1_hole_r: FF2020}
    - duration: 500ms
      lights: {l_1_hole_l: 401010, l_1_hole_r: 401010}
  spider_slayer_vuk_flash:
    - duration: 300ms
      lights: {l_gi_left_upper: 30FF60}
    - duration: 300ms
      lights: {l_gi_left_upper: off}
