#config_version=6

mode:
  code: villain_start.VillainStart
  start_events: ball_started
  stop_events: ball_ending
  priority: 116

event_player:
  s_saucer_1_active{current_player.villain_mode_running == 0}:
    - saucer_1_hit

  s_saucer_2_active{current_player.villain_mode_running == 0}:
    - saucer_2_hit

  s_saucer_3_active{current_player.villain_mode_running == 0}:
    - saucer_3_hit

  villain_saucer_points_only:
    - award_villain_saucer_points

  mini_wizard_start_ready_at_daily_bugle:
    - light_daily_bugle_vuk_for_mini_wizard
