#config_version=6

mode:
  start_events: ball_started
  priority: 110



variable_player:
  mode_qualify_villain_locate_started:
    villain_locate_spins:
      action: set
      int: 0
    villain_locate_spins_needed:
      action: set
      int: 3
      

  villain_spinner_locate_progress:
    score: 5000
    villain_locate_spins: 1

  villain_start_ready_set:
    villain_start_ready:
      action: set
      int: 1



event_player:
  #accumulate spins until mode is running
  s_trispinner_opto_active{current_player.villain_mode_running == 0}:
    - villain_spinner_locate_progress
    - villain_spinner_locate_request    
  
  #
  villain_spinner_locate_request{current_player.villain_start_ready == 0}:
    - villain_check_located

  villain_check_located{current_player.villain_locate_spins >= current_player.villain_locate_spins_needed}:
    - villain_start_ready_set
    - villain_start_ready

  villain_start_ready:
    - villain_saucers_solid_lit
    
  s_upper_target_left_active: saucer_1_flash_request
  s_upper_target_center_active: saucer_2_flash_request
  s_upper_target_right_active: saucer_3_flash_request

  saucer_1_flash_request{current_player.villain_start_ready == 1 and current_player.villain_mode_running == 0}:
    - saucer_1_select_ready_set
    - saucer_1_flash_lit

  saucer_2_flash_request{current_player.villain_start_ready == 1 and current_player.villain_mode_running == 0}:
    - saucer_2_select_ready_set
    - saucer_2_flash_lit

  saucer_3_flash_request{current_player.villain_start_ready == 1 and current_player.villain_mode_running == 0}:
    - saucer_3_select_ready_set
    - saucer_3_flash_lit



#shows for locate, start, select 
show_player:

  saucer_1_flash_lit:
    villain_saucer_1_solid:
      action: stop
    villain_saucer_1_flash:
      loops: -1

  saucer_2_flash_lit:
    villain_saucer_2_solid:
      action: stop
    villain_saucer_2_flash:
      loops: -1

  saucer_3_flash_lit:
    villain_saucer_3_solid:
      action: stop
    villain_saucer_3_flash:
      loops: -1

  villain_spinner_locate_progress:
    villain_spinner_progress_show:
      loops: 1

  villain_saucers_solid_lit:
    villain_saucer_1_solid:
      loops: -1
    villain_saucer_2_solid:
      loops: -1
    villain_saucer_3_solid:
      loops: -1

  start_current_villain:
    villain_saucer_1_solid:
      action: stop
    villain_saucer_2_solid:
      action: stop
    villain_saucer_3_solid:
      action: stop
    villain_saucer_1_flash:
      action: stop
    villain_saucer_2_flash:
      action: stop
    villain_saucer_3_flash:
      action: stop

  start_mode_villain_select:
    villain_saucer_1_solid:
      action: stop
    villain_saucer_2_solid:
      action: stop
    villain_saucer_3_solid:
      action: stop
    villain_saucer_1_flash:
      action: stop
    villain_saucer_2_flash:
      action: stop
    villain_saucer_3_flash:
      action: stop

  carousel_rhino_highlighted:
    villain_select_rhino_show:
      loops: 1

  carousel_sandman_highlighted:
    villain_select_sandman_show:
      loops: 1

  carousel_vulture_highlighted:
    villain_select_vulture_show:
      loops: 1

  carousel_electro_highlighted:
    villain_select_electro_show:
      loops: 1

  carousel_goblin_highlighted:
    villain_select_goblin_show:
      loops: 1

  carousel_mysterio_highlighted:
    villain_select_mysterio_show:
      loops: 1

  carousel_scorpion_highlighted:
    villain_select_scorpion_show:
      loops: 1

  carousel_doc_ock_highlighted:
    villain_select_doc_ock_show:
      loops: 1

  carousel_parafino_highlighted:
    villain_select_parafino_show:
      loops: 1

  carousel_lizard_highlighted:
    villain_select_lizard_show:
      loops: 1




shows:
  villain_spinner_progress_show:
    - duration: 100ms
      lights:
        l_spinner: white
    - duration: 100ms
      lights:
        l_spinner: blue

  villain_select_rhino_show:
    - duration: 250ms
      lights:
        l_left_b: red

  villain_select_sandman_show:
    - duration: 250ms
      lights:
        l_spinner: yellow

  villain_select_vulture_show:
    - duration: 250ms
      lights:
        l_upper_middle: white

  villain_select_electro_show:
    - duration: 250ms
      lights:
        l_a_rollover: blue
        l_b_rollover: blue

  villain_select_goblin_show:
    - duration: 250ms
      lights:
        l_3_hole_l: green

  villain_select_mysterio_show:
    - duration: 250ms
      lights:
        l_star: purple

  villain_select_scorpion_show:
    - duration: 250ms
      lights:
        l_right_a: orange

  villain_select_doc_ock_show:
    - duration: 250ms
      lights:
        l_left_web_target: white
        l_mid_spider_target: white

  villain_select_parafino_show:
    - duration: 250ms
      lights:
        l_5bank_3: yellow

  villain_select_lizard_show:
    - duration: 250ms
      lights:
        l_1_hole_l: green

  villain_saucer_1_flash:
    - duration: 250ms
      lights:
        l_1_hole_l: red
        l_1: red
        l_1_hole_r: red
    - duration: 250ms
      lights:
        l_1_hole_l: off
        l_1: off
        l_1_hole_r: off

  villain_saucer_2_flash:
    - duration: 250ms
      lights:
        l_2_hole_l: red
        l_2: red
        l_2_hole_r: red
    - duration: 250ms
      lights:
        l_2_hole_l: off
        l_2: off
        l_2_hole_r: off

  villain_saucer_3_flash:
    - duration: 250ms
      lights:
        l_3_hole_l: red
        l_3: red
        l_3_hole_r: red
    - duration: 250ms
      lights:
        l_3_hole_l: off
        l_3: off
        l_3_hole_r: off

  villain_saucer_1_solid:
    - duration: 1s
      lights:
        l_1_hole_l: white
        l_1: white
        l_1_hole_r: white

  villain_saucer_2_solid:
    - duration: 1s
      lights:
        l_2_hole_l: white
        l_2: white
        l_2_hole_r: white

  villain_saucer_3_solid:
    - duration: 1s
      lights:
        l_3_hole_l: white
        l_3: white
        l_3_hole_r: white
