#config_version=6

mode:
  start_events: ball_started
  priority: 110



variable_player:
  mode_qualify_villain_locate_started:
    villain_locate_spins:
      action: set
      int: 0
    villain_locate_spins_needed:
      action: set
      int: 3
      

  villain_spinner_locate_progress:
    score: 5000
    villain_locate_spins: 1

  villain_start_ready_set:
    villain_start_ready:
      action: set
      int: 1



event_player:
  #accumulate spins until mode is running
  s_trispinner_opto_active{current_player.villain_mode_running == 0}:
    - villain_spinner_locate_progress
    - villain_spinner_locate_request    
  
  #
  villain_spinner_locate_request{current_player.villain_start_ready == 0}:
    - villain_check_located

  villain_check_located{current_player.villain_locate_spins >= current_player.villain_locate_spins_needed}:
    - villain_start_ready_set
    - villain_start_ready

  villain_start_ready:
    - villain_saucers_solid_lit
    
  s_upper_target_left_active: saucer_1_flash_request
  s_upper_target_center_active: saucer_2_flash_request
  s_upper_target_right_active: saucer_3_flash_request

  saucer_1_flash_request{current_player.villain_start_ready == 1 and current_player.villain_mode_running == 0}:
    - saucer_1_select_ready_set
    - saucer_1_flash_lit

  saucer_2_flash_request{current_player.villain_start_ready == 1 and current_player.villain_mode_running == 0}:
    - saucer_2_select_ready_set
    - saucer_2_flash_lit

  saucer_3_flash_request{current_player.villain_start_ready == 1 and current_player.villain_mode_running == 0}:
    - saucer_3_select_ready_set
    - saucer_3_flash_lit


 



show_player:

  saucer_1_flash_lit:
    villain_saucer_1_solid:
      action: stop
    villain_saucer_1_flash:
      loops: -1

  saucer_2_flash_lit:
    villain_saucer_2_solid:
      action: stop
    villain_saucer_2_flash:
      loops: -1

  saucer_3_flash_lit:
    villain_saucer_3_solid:
      action: stop
    villain_saucer_3_flash:
      loops: -1

  villain_spinner_locate_progress:
    villain_spinner_progress_show:
      loops: 1

  villain_saucers_solid_lit:
    villain_saucer_1_solid:
      loops: -1
    villain_saucer_2_solid:
      loops: -1
    villain_saucer_3_solid:
      loops: -1

  start_current_villain:
    villain_saucer_1_solid:
      action: stop
    villain_saucer_2_solid:
      action: stop
    villain_saucer_3_solid:
      action: stop
    villain_saucer_1_flash:
      action: stop
    villain_saucer_2_flash:
      action: stop
    villain_saucer_3_flash:
      action: stop


shows:
  villain_spinner_progress_show:
    - duration: 100ms
      lights:
        l_spinner: white
    - duration: 100ms
      lights:
        l_spinner: blue

