#config_version=6

mode:
  start_events: start_mode_lizard
  stop_events:
    - lizard_mode_complete
    - lizard_mode_completed_summary
    - ball_ended
  code: lizard.Lizard
  priority: 300


widget_player:
  mode_lizard_started:
    lizard:
      action: play

  lizard_mode_complete:
    lizard:
      action: remove

  mode_lizard_stopping:
    lizard:
      action: remove

random_event_player:
  lizard_serum_collected:
    - lizard_serum_collected_1
    - lizard_serum_collected_2
    - lizard_serum_collected_3

sound_player:
  lizard_serum_collected_1:
    sm_i_have_to_hurry:
      action: play
      bus: voice

  lizard_serum_collected_2:
    sm_I_need_to_get_this_to_the_lizard_man:
      action: play
      bus: voice

  lizard_serum_collected_3:
    sm_I_need_to_deliver:
      action: play
      bus: voice

  lizard_light_serum_location{current_player.lizard_deliveries == 0}:
    sm_i_need_to_get_the_antidote:
      action: play
      bus: voice

  lizard_light_serum_location{current_player.lizard_deliveries > 0}:
    sm_i_need_to_get_more_antidote:
      action: play
      bus: voice


event_player:
  drop_target_bank_dt_bank_left_down:
    - drop_target_bank_dt_bank_left_reset

  drop_target_bank_dt_bank_right_down:
    - drop_target_bank_dt_bank_right_reset

  s_saucer_1_active:
    - clear_saucers

  s_saucer_2_active:
    - clear_saucers

  s_saucer_3_active:
    - clear_saucers


timers:

  lizard_delivery_timer:
    start_value: 12
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: lizard_delivery_timer_start
        action: restart
      - event: lizard_delivery_timer_stop
        action: stop

  lizard_followup_timer:
    start_value: 5
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: lizard_followup_timer_start
        action: restart
      - event: lizard_followup_timer_stop
        action: stop
      - event: lizard_mode_complete
        action: stop

show_player:

  lizard_light_serum_location:
    lizard_gi_show:
      loops: -1
    lizard_serum_star_show:
      loops: -1
    lizard_left_web_show:
      action: stop
    lizard_center_web_show:
      action: stop

  lizard_serum_collected:
    lizard_serum_star_show:
      action: stop
    lizard_gi_show:
      action: stop
    lizard_gi_hurry_show:
      loops: -1

  lizard_light_left_web:
    lizard_left_web_show:
      loops: -1

  lizard_light_center_web:
    lizard_center_web_show:
      loops: -1

  lizard_light_both_webs:
    lizard_left_web_show:
      loops: -1
    lizard_center_web_show:
      loops: -1

  lizard_serum_delivered:
    lizard_left_web_show:
      action: stop
    lizard_center_web_show:
      action: stop
    lizard_gi_show:
      action: stop
    lizard_gi_hurry_show:
      action: stop

  lizard_followup_collected:
    lizard_left_web_show:
      action: stop
    lizard_center_web_show:
      action: stop

  lizard_followup_expired:
    lizard_left_web_show:
      action: stop
    lizard_center_web_show:
      action: stop

  lizard_followup_cleanup:
    lizard_left_web_show:
      action: stop
    lizard_center_web_show:
      action: stop

  lizard_serum_expired_show:
    lizard_left_web_show:
      action: stop
    lizard_center_web_show:
      action: stop
    lizard_gi_show:
      action: stop
    lizard_gi_hurry_show:
      action: stop

  lizard_mode_complete:
    lizard_serum_star_show:
      action: stop
    lizard_left_web_show:
      action: stop
    lizard_center_web_show:
      action: stop
    lizard_complete_show:
      loops: 1
    lizard_gi_show:
      action: stop
    lizard_gi_hurry_show:
      action: stop

  lizard_a_complete:
    lizard_a_complete_show:
      loops: -1

  lizard_b_complete:
    lizard_b_complete_show:
      loops: -1

  lizard_ab_complete:
    lizard_a_complete_show:
      action: stop
    lizard_b_complete_show:
      action: stop
    lizard_ab_ready_show:
      loops: 3

  lizard_clear_ab:
    lizard_ab_off_show:
      loops: 1


shows:

  lizard_gi_show:
    - duration: 400ms
      lights:
        gi: B0FFB0
    - duration: 200ms
      lights:
        gi: D0FFD0
    - duration: 100ms
      lights:
        gi: FFFFFF

  lizard_gi_hurry_show:
    - duration: 400ms
      lights:
        gi: FFFFB0
    - duration: 200ms
      lights:
        gi: FFFFD0
    - duration: 100ms
      lights:
        gi: FFFFFF

  lizard_serum_star_show:
    - duration: 500ms
      lights:
        l_star: white
    - duration: 500ms
      lights:
        l_star: off

  lizard_left_web_show:
    - duration: 250ms
      lights:
        l_left_web_target: green
    - duration: 250ms
      lights:
        l_left_web_target: white

  lizard_center_web_show:
    - duration: 250ms
      lights:
        l_mid_web_target: green
    - duration: 250ms
      lights:
        l_mid_web_target: white

  lizard_delivery_success_show:
    - duration: 150ms
      lights:
        l_left_web_target: white
        l_mid_web_target: white
    - duration: 150ms
      lights:
        l_left_web_target: green
        l_mid_web_target: green

  lizard_serum_expired_lights:
    - duration: 150ms
      lights:
        l_star: red
        l_left_web_target: red
        l_mid_web_target: red
    - duration: 150ms
      lights:
        l_star: off
        l_left_web_target: off
        l_mid_web_target: off

  lizard_complete_show:
    - duration: 200ms
      lights:
        gi: green
    - duration: 200ms
      lights:
        gi: white

  lizard_a_complete_show:
    - duration: 300ms
      lights:
        l_a_rollover: white
        l_right_a: white
    - duration: 300ms
      lights:
        l_a_rollover: blue
        l_right_a: blue

  lizard_b_complete_show:
    - duration: 300ms
      lights:
        l_b_rollover: white
        l_left_b: white
    - duration: 300ms
      lights:
        l_b_rollover: blue
        l_left_b: blue

  lizard_ab_off_show:
    - duration: 300ms
      lights:
        l_a_rollover: off
        l_right_a: off
        l_b_rollover: off
        l_left_b: off

  lizard_ab_ready_show:
    - duration: 300ms
      lights:
        l_a_rollover: white
        l_right_a: white
        l_b_rollover: white
        l_left_b: white
    - duration: 300ms
      lights:
        l_a_rollover: blue
        l_b_rollover: blue
        l_right_a: blue
        l_left_b: blue
