#config_version=6

mode:
  start_events: start_mode_lizard
  stop_events:
    - ball_will_end
    - bonus_start
    - lizard_mode_complete
    - lizard_mode_completed_summary
    - ball_ended
  code: lizard.Lizard
  priority: 300


widget_player:
  mode_lizard_started:
    lizard:
      action: play

  lizard_mode_complete:
    lizard:
      action: remove

  mode_lizard_stopping:
    lizard:
      action: remove

random_event_player:
  lizard_serum_collected:
    - lizard_serum_collected_1
    - lizard_serum_collected_2
    - lizard_serum_collected_3

sound_player:
  play_mode_jackpot:
    jackpot_2:
      action: play
      bus: effects
  play_mode_super_jackpot:
    jackpot_2:
      action: play
      bus: effects
  lizard_serum_collected_1:
    sm_i_have_to_hurry:
      action: play
      bus: voice

  lizard_serum_collected_2:
    sm_I_need_to_get_this_to_the_lizard_man:
      action: play
      bus: voice

  lizard_serum_collected_3:
    sm_I_need_to_deliver:
      action: play
      bus: voice

  lizard_light_serum_location{current_player.lizard_deliveries == 0}:
    sm_i_need_to_get_the_antidote:
      action: play
      bus: voice

  lizard_light_serum_location{current_player.lizard_deliveries > 0}:
    sm_i_need_to_get_more_antidote:
      action: play
      bus: voice


event_player:
  drop_target_bank_dt_bank_left_down:
    - drop_target_bank_dt_bank_left_reset

  drop_target_bank_dt_bank_right_down:
    - drop_target_bank_dt_bank_right_reset

  s_saucer_1_active:
    - clear_saucers

  s_saucer_2_active:
    - clear_saucers

  s_saucer_3_active:
    - clear_saucers


timers:

  lizard_delivery_timer:
    start_value: 16
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: lizard_delivery_timer_start
        action: restart
      - event: lizard_delivery_timer_stop
        action: stop
      - event: mode_lizard_stopping
        action: stop

  lizard_delivery_timer_more_time:
    start_value: 20
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: lizard_delivery_timer_more_time_start
        action: restart
      - event: lizard_delivery_timer_more_time_stop
        action: stop
      - event: mode_lizard_stopping
        action: stop

show_player:

  lizard_light_serum_location:
    lizard_gi_show:
      loops: -1
    lizard_left_web_show:
      action: stop

  lizard_serum_collected:
    lizard_left_pop_available_show:
      action: stop
    lizard_right_pop_available_show:
      action: stop
    lizard_left_pop_collected_show:
      action: stop
    lizard_right_pop_collected_show:
      action: stop
    lizard_gi_show:
      action: stop
    lizard_gi_hurry_show:
      loops: -1

  lizard_pop_left_available:
    lizard_left_pop_collected_show:
      action: stop
    lizard_left_pop_available_show:
      loops: -1
      priority: 340

  lizard_pop_right_available:
    lizard_right_pop_collected_show:
      action: stop
    lizard_right_pop_available_show:
      loops: -1
      priority: 340

  lizard_pop_left_collected:
    lizard_left_pop_available_show:
      action: stop
    lizard_left_pop_collected_show:
      loops: -1
      priority: 340

  lizard_pop_right_collected:
    lizard_right_pop_available_show:
      action: stop
    lizard_right_pop_collected_show:
      loops: -1
      priority: 340

  lizard_star_10x_available:
    lizard_star_10x_armed_show:
      action: stop
    lizard_star_10x_available_show:
      loops: -1

  lizard_star_10x_armed:
    lizard_star_10x_available_show:
      action: stop
    lizard_star_10x_armed_show:
      loops: -1

  lizard_star_10x_stop:
    lizard_star_10x_available_show:
      action: stop
    lizard_star_10x_armed_show:
      action: stop

  lizard_light_left_web:
    lizard_left_web_show:
      loops: -1

  lizard_serum_delivered:
    lizard_left_web_show:
      action: stop
    lizard_star_10x_available_show:
      action: stop
    lizard_star_10x_armed_show:
      action: stop
    lizard_gi_show:
      action: stop
    lizard_gi_hurry_show:
      action: stop
    lizard_delivery_success_show:
      loops: 0

  lizard_serum_expired_show:
    lizard_left_web_show:
      action: stop
    lizard_star_10x_available_show:
      action: stop
    lizard_star_10x_armed_show:
      action: stop
    lizard_gi_show:
      action: stop
    lizard_gi_hurry_show:
      action: stop
    lizard_serum_expired_lights:
      loops: 0

  lizard_mode_complete:
    lizard_left_pop_available_show:
      action: stop
    lizard_right_pop_available_show:
      action: stop
    lizard_left_pop_collected_show:
      action: stop
    lizard_right_pop_collected_show:
      action: stop
    lizard_star_10x_available_show:
      action: stop
    lizard_star_10x_armed_show:
      action: stop
    lizard_left_web_show:
      action: stop
    lizard_complete_show:
      loops: 1
    lizard_gi_show:
      action: stop
    lizard_gi_hurry_show:
      action: stop

  lizard_a_complete:
    lizard_a_available_show:
      action: stop
    lizard_a_collected_show:
      loops: -1

  lizard_b_complete:
    lizard_b_available_show:
      action: stop
    lizard_b_collected_show:
      loops: -1

  lizard_ab_complete:
    lizard_a_collected_show:
      loops: -1
    lizard_b_collected_show:
      loops: -1

  lizard_ab_timer_restarted:
    lizard_ab_gi_show:
      loops: 2

  lizard_clear_ab:
    lizard_a_collected_show:
      action: stop
    lizard_b_collected_show:
      action: stop
    lizard_a_available_show:
      loops: -1
    lizard_b_available_show:
      loops: -1


shows:

  lizard_gi_show:
    - duration: 1.5s
      lights:
        gi:
          color: F0F040
          fade: 1.5s
    - duration: 1.5s
      lights:
        gi:
          color: F02040
          fade: 1.5s

  lizard_gi_hurry_show:
    - duration: 1.25s
      lights:
        gi: "406060"
    - duration: 250ms
      lights:
        gi: F02040

  lizard_left_pop_available_show:
    - duration: 400ms
      lights:
        l_pop_1_1: purple
        l_pop_1_2: purple
        l_pop_1_3: purple
        l_pop_1_4: purple
        l_pop_1_5: purple
        l_pop_1_6: purple
        l_pop_1_7: purple
        l_pop_1_8: purple
        l_pop_1_9: purple
        l_pop_1_10: purple
        l_pop_1_11: purple
        l_pop_1_12: purple
    - duration: 400ms
      lights:
        l_pop_1_1: off
        l_pop_1_2: off
        l_pop_1_3: off
        l_pop_1_4: off
        l_pop_1_5: off
        l_pop_1_6: off
        l_pop_1_7: off
        l_pop_1_8: off
        l_pop_1_9: off
        l_pop_1_10: off
        l_pop_1_11: off
        l_pop_1_12: off

  lizard_right_pop_available_show:
    - duration: 400ms
      lights:
        l_pop_2_1: purple
        l_pop_2_2: purple
        l_pop_2_3: purple
        l_pop_2_4: purple
        l_pop_2_5: purple
        l_pop_2_6: purple
        l_pop_2_7: purple
        l_pop_2_8: purple
        l_pop_2_9: purple
        l_pop_2_10: purple
        l_pop_2_11: purple
        l_pop_2_12: purple
    - duration: 400ms
      lights:
        l_pop_2_1: off
        l_pop_2_2: off
        l_pop_2_3: off
        l_pop_2_4: off
        l_pop_2_5: off
        l_pop_2_6: off
        l_pop_2_7: off
        l_pop_2_8: off
        l_pop_2_9: off
        l_pop_2_10: off
        l_pop_2_11: off
        l_pop_2_12: off

  lizard_left_pop_collected_show:
    - duration: 1s
      lights:
        l_pop_1_1: purple
        l_pop_1_2: purple
        l_pop_1_3: purple
        l_pop_1_4: purple
        l_pop_1_5: purple
        l_pop_1_6: purple
        l_pop_1_7: purple
        l_pop_1_8: purple
        l_pop_1_9: purple
        l_pop_1_10: purple
        l_pop_1_11: purple
        l_pop_1_12: purple

  lizard_right_pop_collected_show:
    - duration: 1s
      lights:
        l_pop_2_1: purple
        l_pop_2_2: purple
        l_pop_2_3: purple
        l_pop_2_4: purple
        l_pop_2_5: purple
        l_pop_2_6: purple
        l_pop_2_7: purple
        l_pop_2_8: purple
        l_pop_2_9: purple
        l_pop_2_10: purple
        l_pop_2_11: purple
        l_pop_2_12: purple

  lizard_star_10x_available_show:
    - duration: 250ms
      lights:
        l_star: red
    - duration: 250ms
      lights:
        l_star: off

  lizard_star_10x_armed_show:
    - duration: 1s
      lights:
        l_star: red

  lizard_left_web_show:
    - duration: 250ms
      lights:
        l_left_web_target: purple
    - duration: 250ms
      lights:
        l_left_web_target: off

  lizard_delivery_success_show:
    - duration: 500ms
      lights:
        l_left_web_target: white
    - duration: 500ms
      lights:
        l_left_web_target: green
    - duration: 500ms
      lights:
        l_left_web_target: white
    - duration: 500ms
      lights:
        l_left_web_target: green

  lizard_serum_expired_lights:
    - duration: 2s
      lights:
        gi:
          color: off
          fade: 2s

  lizard_complete_show:
    - duration: 200ms
      lights:
        gi: green
    - duration: 200ms
      lights:
        gi: white

  lizard_a_available_show:
    - duration: 300ms
      lights:
        l_a_rollover: yellow
        l_right_a: yellow
    - duration: 300ms
      lights:
        l_a_rollover: off
        l_right_a: off

  lizard_b_available_show:
    - duration: 300ms
      lights:
        l_b_rollover: yellow
        l_left_b: yellow
    - duration: 300ms
      lights:
        l_b_rollover: off
        l_left_b: off

  lizard_a_collected_show:
    - duration: 1s
      lights:
        l_a_rollover: yellow
        l_right_a: yellow

  lizard_b_collected_show:
    - duration: 1s
      lights:
        l_b_rollover: yellow
        l_left_b: yellow

  lizard_ab_gi_show:
    - duration: 100ms
      lights:
        gi: green
    - duration: 100ms
      lights:
        gi: yellow
    - duration: 100ms
      lights:
        gi: white
    - duration: 100ms
      lights:
        gi: off
