#config_version=6

mode:
  start_events: start_mode_mysterio
  stop_events: mysterio_mode_complete, ball_ended
  code: mysterio.Mysterio
  priority: 500

event_player:
  mysterio_mode_complete:
    - reset_villain_locate

  mode_mysterio_started:
    - clear_saucers

  s_left_web_target_active: mysterio_left_web_hit
  s_web_target_top_active: mysterio_right_web_hit
  s_web_spinner_active: mysterio_spinner_hit
  left_drops_hit: mysterio_left_drops_hit
  right_drops_hit: mysterio_right_drops_hit
  s_trispinner_opto_active: mysterio_upper_spinner_hit
  saucers_hit: mysterio_saucers_hit
  upper_targets_hit: mysterio_upper_target_hit

  mysterio_all_shots_lit:
    - mysterio_lite_left_web
    - mysterio_lite_right_web
    - mysterio_lite_spinner
    - mysterio_lite_left_drops
    - mysterio_lite_right_drops
    - mysterio_lite_upper_spinner
    - mysterio_lite_saucers
    - mysterio_lite_upper_target


shot_groups:
  right_drops:
    shots: right_drop_1, right_drop_2, right_drop_3, right_drop_4, right_drop_5

  left_drops:
    shots: left_drop_1, left_drop_3, left_drop_3

  upper_targets:
    shots: upper_target_left, upper_target_center, upper_target_right

  saucers:
    shots: saucer_1, saucer_2, saucer_3

shots:

  saucer_1:
    switch: s_saucer_1

  saucer_2:
    switch: s_saucer_2

  saucer_3:
    switch: s_saucer_3

  upper_target_left:
    switch: s_upper_target_left

  upper_target_center:
    switch: s_upper_target_center

  upper_target_right:
    switch: s_upper_target_right

  right_drop_1:
    switch: s_right_drops_1

  right_drop_2:
    switch: s_right_drops_2

  right_drop_3:
    switch: s_right_drops_3

  right_drop_4:
    switch: s_right_drops_4

  right_drop_5:
    switch: s_right_drops_5

  left_drop_1:
    switch: s_left_drops_1

  left_drop_2:
    switch: s_left_drops_2

  left_drop_3:
    switch: s_left_drops_3

variable_player:
  mysterio_score_wrong_shot:
    score:
      action: add
      int: 50000

  mysterio_super_collected:
    score:
      action: add
      int: current_player.mysterio_award_value

show_player:
#  mysterio_trial_started:
#    mysterio_start_show:
#      loops: 0
#
#  mysterio_spidey_sense_left:
#    mysterio_hint_left_show:
#      loops: 0
#
#  mysterio_spidey_sense_right:
#    mysterio_hint_right_show:
#      loops: 0
#
#  mysterio_spidey_sense_upper:
#    mysterio_hint_upper_show:
#      loops: 0
#
#  mysterio_super_collected:
#    mysterio_super_show:
#      loops: 0
      
  mysterio_lite_left_web:
    mysterio_lite_left_web_show:
      loops: -1

  mysterio_lite_right_web:
    mysterio_lite_right_web_show:
      loops: -1

  mysterio_lite_spinner:
    mysterio_lite_spinner_show:
      loops: -1

  mysterio_lite_left_drops:
    mysterio_lite_left_drops_show:
      loops: -1

  mysterio_lite_right_drops:
    mysterio_lite_right_drops_show:
      loops: -1

  mysterio_lite_upper_spinner:
    mysterio_lite_upper_spinner_show:
      loops: -1

  mysterio_lite_saucers:
    mysterio_lite_saucers_show:
      loops: -1

  mysterio_lite_upper_target:
    mysterio_lite_upper_target_show:
      loops: -1

  mysterio_stop_left_web:
    mysterio_lite_left_web_show:
      action: stop

  mysterio_stop_right_web:
    mysterio_lite_right_web_show:
      action: stop

  mysterio_stop_spinner:
    mysterio_lite_spinner_show:
      action: stop

  mysterio_stop_left_drops:
    mysterio_lite_left_drops_show:
      action: stop

  mysterio_stop_right_drops:
    mysterio_lite_right_drops_show:
      action: stop

  mysterio_stop_upper_spinner:
    mysterio_lite_upper_spinner_show:
      action: stop

  mysterio_stop_saucers:
    mysterio_lite_saucers_show:
      action: stop

  mysterio_stop_upper_target:
    mysterio_lite_upper_target_show:
      action: stop


shows:

  mysterio_lite_left_web_show:
    - duration: 120ms
      lights:
        l_left_web_target: yellow
    - duration: 120ms
      lights:
        l_left_web_target: blue

  mysterio_lite_right_web_show:
    - duration: 120ms
      lights:
        l_mid_spider_target: yellow
    - duration: 120ms
      lights:
        l_mid_spider_target: blue

  mysterio_lite_spinner_show:
    - duration: 120ms
      lights:
        l_spinner: yellow
    - duration: 120ms
      lights:
        l_spinner: blue

  mysterio_lite_left_drops_show:
    - duration: 120ms
      lights:
        l_3bankbonus: yellow
        l_left_multibonus: yellow
    - duration: 120ms
      lights:
        l_3bankbonus: blue
        l_left_multibonus: blue

  mysterio_lite_right_drops_show:
    - duration: 120ms
      lights:
        l_5bank_1: yellow
        l_5bank_2: yellow
        l_5bank_3: yellow
        l_5bank_4: yellow
        l_5bank_5: yellow
    - duration: 120ms
      lights:
        l_5bank_1: blue
        l_5bank_2: blue
        l_5bank_3: blue
        l_5bank_4: blue
        l_5bank_5: blue

  mysterio_lite_upper_spinner_show:
    - duration: 120ms
      lights:
        l_gi_a: yellow
    - duration: 120ms
      lights:
        l_gi_a: blue

  mysterio_lite_saucers_show:
    - duration: 120ms
      lights:
        l_1_hole_l: yellow
        l_1: yellow
        l_1_hole_r: yellow
        l_2_hole_l: yellow
        l_2: yellow
        l_2_hole_r: yellow
        l_3_hole_l: yellow
        l_3: yellow
        l_3_hole_r: yellow
    - duration: 120ms
      lights:
        l_1_hole_l: blue
        l_1: blue
        l_1_hole_r: blue
        l_2_hole_l: blue
        l_2: blue
        l_2_hole_r: blue
        l_3_hole_l: blue
        l_3: blue
        l_3_hole_r: blue

  mysterio_lite_upper_target_show:
    - duration: 120ms
      lights:
        l_upper_left: yellow
        l_upper_middle: yellow
        l_upper_right: yellow
    - duration: 120ms
      lights:
        l_upper_left: blue
        l_upper_middle: blue
        l_upper_right: blue
