#config_version=6

mode:
  code: qualify_system.QualifySystem
  start_events: ball_started
  stop_events: ball_ending
  priority: 115

event_player:
  villain_qualify_drop_bank_reset_request:
    - drop_target_bank_dt_bank_left_reset

  s_left_drops_1_active:
    - villain_qualify_drop_1_hit

  s_left_drops_2_active:
    - villain_qualify_drop_2_hit

  s_left_drops_3_active:
    - villain_qualify_drop_3_hit

  s_star_rollover_active:
    - saucer_star_upgrade_hit

show_player:
  clear_villain_saucer_lights:
    saucer_cluster_state_0:
      action: stop
    saucer_cluster_state_1:
      action: stop
    saucer_cluster_state_2:
      action: stop
    saucer_cluster_state_3:
      action: stop

      
  saucer_1_restore_state_0:
    saucer_cluster_state_0:
      key: saucer_1
      show_tokens:
        main_light: l_1
        hole_left: l_1_hole_l
        hole_right: l_1_hole_r

  saucer_1_restore_state_1:
    saucer_cluster_state_1:
      key: saucer_1
      show_tokens:
        main_light: l_1
        hole_left: l_1_hole_l
        hole_right: l_1_hole_r

  saucer_1_restore_state_2:
    saucer_cluster_state_2:
      key: saucer_1
      show_tokens:
        main_light: l_1
        hole_left: l_1_hole_l
        hole_right: l_1_hole_r

  saucer_1_restore_state_3:
    saucer_cluster_state_3:
      key: saucer_1
      show_tokens:
        main_light: l_1
        hole_left: l_1_hole_l
        hole_right: l_1_hole_r

  saucer_1_restore_state_4:
    saucer_cluster_state_4:
      key: saucer_1
      show_tokens:
        main_light: l_1
        hole_left: l_1_hole_l
        hole_right: l_1_hole_r

  saucer_1_restore_state_5:
    saucer_cluster_state_5:
      key: saucer_1
      show_tokens:
        main_light: l_1
        hole_left: l_1_hole_l
        hole_right: l_1_hole_r

  saucer_2_restore_state_0:
    saucer_cluster_state_0:
      key: saucer_2
      show_tokens:
        main_light: l_2
        hole_left: l_2_hole_l
        hole_right: l_2_hole_r

  saucer_2_restore_state_1:
    saucer_cluster_state_1:
      key: saucer_2
      show_tokens:
        main_light: l_2
        hole_left: l_2_hole_l
        hole_right: l_2_hole_r

  saucer_2_restore_state_2:
    saucer_cluster_state_2:
      key: saucer_2
      show_tokens:
        main_light: l_2
        hole_left: l_2_hole_l
        hole_right: l_2_hole_r

  saucer_2_restore_state_3:
    saucer_cluster_state_3:
      key: saucer_2
      show_tokens:
        main_light: l_2
        hole_left: l_2_hole_l
        hole_right: l_2_hole_r

  saucer_2_restore_state_4:
    saucer_cluster_state_4:
      key: saucer_2
      show_tokens:
        main_light: l_2
        hole_left: l_2_hole_l
        hole_right: l_2_hole_r

  saucer_2_restore_state_5:
    saucer_cluster_state_5:
      key: saucer_2
      show_tokens:
        main_light: l_2
        hole_left: l_2_hole_l
        hole_right: l_2_hole_r

  saucer_3_restore_state_0:
    saucer_cluster_state_0:
      key: saucer_3
      show_tokens:
        main_light: l_3
        hole_left: l_3_hole_l
        hole_right: l_3_hole_r

  saucer_3_restore_state_1:
    saucer_cluster_state_1:
      key: saucer_3
      show_tokens:
        main_light: l_3
        hole_left: l_3_hole_l
        hole_right: l_3_hole_r

  saucer_3_restore_state_2:
    saucer_cluster_state_2:
      key: saucer_3
      show_tokens:
        main_light: l_3
        hole_left: l_3_hole_l
        hole_right: l_3_hole_r

  saucer_3_restore_state_3:
    saucer_cluster_state_3:
      key: saucer_3
      show_tokens:
        main_light: l_3
        hole_left: l_3_hole_l
        hole_right: l_3_hole_r

  saucer_3_restore_state_4:
    saucer_cluster_state_4:
      key: saucer_3
      show_tokens:
        main_light: l_3
        hole_left: l_3_hole_l
        hole_right: l_3_hole_r

  saucer_3_restore_state_5:
    saucer_cluster_state_5:
      key: saucer_3
      show_tokens:
        main_light: l_3
        hole_left: l_3_hole_l
        hole_right: l_3_hole_r

shows:
  saucer_cluster_state_0:
    - duration: -1
      lights:
        (main_light): off
        (hole_left): off
        (hole_right): off

  saucer_cluster_state_1:
    - duration: 500ms
      lights:
        (main_light): blue
        (hole_left): off
        (hole_right): off
    - duration: 500ms
      lights:
        (main_light): off
        (hole_left): off
        (hole_right): off

  saucer_cluster_state_2:
    - duration: 350ms
      lights:
        (main_light): blue
        (hole_left): white
        (hole_right): white
    - duration: 350ms
      lights:
        (main_light): off
        (hole_left): off
        (hole_right): off

  saucer_cluster_state_3:
    - duration: 250ms
      lights:
        (main_light): green
        (hole_left): white
        (hole_right): white
    - duration: 250ms
      lights:
        (main_light): off
        (hole_left): off
        (hole_right): off

  saucer_cluster_state_4:
    - duration: 180ms
      lights:
        (main_light): green
        (hole_left): red
        (hole_right): red
    - duration: 180ms
      lights:
        (main_light): off
        (hole_left): off
        (hole_right): off

  saucer_cluster_state_5:
    - duration: 100ms
      lights:
        (main_light): white
        (hole_left): red
        (hole_right): red
    - duration: 100ms
      lights:
        (main_light): green
        (hole_left): off
        (hole_right): off
