#config_version=6

mode:
  start_events: ball_started
  priority: 120

variable_player:
  mode_qualify_villain_start_started:
    villain_current_index:
      action: set
      int: 1
    villain_mode_running:
      action: set
      int: 0
    villain_start_ready:
      action: set
      int: 0
    saucer_1_select_ready:
      action: set
      int: 0
    saucer_2_select_ready:
      action: set
      int: 0
    saucer_3_select_ready:
      action: set
      int: 0
    villains_completed_total:
      action: set
      int: 0
    kingpin_ready:
      action: set
      int: 0

  villain_started_set:
    villain_mode_running:
      action: set
      int: 1
    villain_start_ready:
      action: set
      int: 0
    villain_locate_spins:
      action: set
      int: 0
    saucer_1_select_ready:
      action: set
      int: 0
    saucer_2_select_ready:
      action: set
      int: 0
    saucer_3_select_ready:
      action: set
      int: 0

  villain_mode_running_clear:
    villain_mode_running:
      action: set
      int: 0

  saucer_1_select_ready_set:
    saucer_1_select_ready:
      action: set
      int: 1

  saucer_2_select_ready_set:
    saucer_2_select_ready:
      action: set
      int: 1

  saucer_3_select_ready_set:
    saucer_3_select_ready:
      action: set
      int: 1

  advance_current_villain:
    villain_current_index: 1

  current_villain_wrap_to_1:
    villain_current_index:
      action: set
      int: 1

  kingpin_ready_set:
    kingpin_ready:
      action: set
      int: 1





event_player:

  s_saucer_1_active: saucer_1_villain_start_request
  s_saucer_2_active: saucer_2_villain_start_request
  s_saucer_3_active: saucer_3_villain_start_request


  saucer_1_villain_start_request{current_player.saucer_1_select_ready == 1}: start_mode_villain_select
  saucer_1_villain_start_request{current_player.villain_start_ready == 1 and current_player.saucer_1_select_ready == 0}: start_current_villain

  saucer_2_villain_start_request{current_player.saucer_2_select_ready == 1}: start_mode_villain_select
  saucer_2_villain_start_request{current_player.villain_start_ready == 1 and current_player.saucer_2_select_ready == 0}: start_current_villain

  saucer_3_villain_start_request{current_player.saucer_3_select_ready == 1}: start_mode_villain_select
  saucer_3_villain_start_request{current_player.villain_start_ready == 1 and current_player.saucer_3_select_ready == 0}: start_current_villain

  start_current_villain{current_player.kingpin_ready == 1}: start_kingpin_wizard
  start_current_villain{current_player.kingpin_ready == 0 and current_player.villain_current_index == 1}: start_rhino_villain
  start_current_villain{current_player.kingpin_ready == 0 and current_player.villain_current_index == 2}: start_sandman_villain
  start_current_villain{current_player.kingpin_ready == 0 and current_player.villain_current_index == 3}: start_vulture_villain
  start_current_villain{current_player.kingpin_ready == 0 and current_player.villain_current_index == 4}: start_electro_villain
  start_current_villain{current_player.kingpin_ready == 0 and current_player.villain_current_index == 5}: start_goblin_villain
  start_current_villain{current_player.kingpin_ready == 0 and current_player.villain_current_index == 6}: start_mysterio_villain
  start_current_villain{current_player.kingpin_ready == 0 and current_player.villain_current_index == 7}: start_scorpion_villain
  start_current_villain{current_player.kingpin_ready == 0 and current_player.villain_current_index == 8}: start_doc_ock_villain
  start_current_villain{current_player.kingpin_ready == 0 and current_player.villain_current_index == 9}: start_parafino_villain
  start_current_villain{current_player.kingpin_ready == 0 and current_player.villain_current_index == 10}: start_lizard_villain

  check_kingpin_ready{current_player.villains_completed_total >= 10}:
    - kingpin_ready_set
    - kingpin_wizard_ready

  current_villain_wrap_check{current_player.villain_current_index > 10}: current_villain_wrap_to_1
  
  start_rhino_villain:
    - villain_started_set
    - start_mode_rhino_bash

  start_sandman_villain:
    - villain_started_set
    - start_mode_sandman

  start_vulture_villain:
    - villain_started_set
    - start_mode_vulture

  start_electro_villain:
    - villain_started_set
    - start_mode_electro

  start_goblin_villain:
    - villain_started_set
    - start_mode_goblin

  start_mysterio_villain:
    - villain_started_set
    - start_mode_mysterio

  start_scorpion_villain:
    - villain_started_set
    - start_mode_scorpion

  start_doc_ock_villain:
    - villain_started_set
    - start_mode_doc_ock

  start_parafino_villain:
    - villain_started_set
    - start_mode_parafino

  start_lizard_villain:
    - villain_started_set
    - start_mode_lizard

  start_kingpin_wizard:
    - villain_started_set
    - start_mode_kingpin

  villain_mode_ended:
    - villain_mode_running_clear
    - advance_current_villain
    - current_villain_wrap_check


show_player:

  start_mode_villain_select:
    villain_saucer_1_solid:
      action: stop
    villain_saucer_2_solid:
      action: stop
    villain_saucer_3_solid:
      action: stop
    villain_saucer_1_flash:
      action: stop
    villain_saucer_2_flash:
      action: stop
    villain_saucer_3_flash:
      action: stop

  start_current_villain:
    villain_saucer_1_solid:
      action: stop
    villain_saucer_2_solid:
      action: stop
    villain_saucer_3_solid:
      action: stop
    villain_saucer_1_flash:
      action: stop
    villain_saucer_2_flash:
      action: stop
    villain_saucer_3_flash:
      action: stop


shows:
  villain_saucer_1_flash:
    - duration: 250ms
      lights:
        l_1_hole_l: red
    - duration: 250ms
      lights:
        l_1_hole_l: off

  villain_saucer_2_flash:
    - duration: 250ms
      lights:
        l_2_hole_l: red
    - duration: 250ms
      lights:
        l_2_hole_l: off

  villain_saucer_3_flash:
    - duration: 250ms
      lights:
        l_3_hole_l: red
    - duration: 250ms
      lights:
        l_3_hole_l: off