#config_version=6

mode:
  start_events: ball_started
  code: qualify_villain_start.QualifyVillainStart
  priority: 120

variable_player:
  mode_qualify_villain_start_started:
    villain_current_index:
      action: set
      int: 1
    villain_mode_running:
      action: set
      int: 0
    villain_start_ready:
      action: set
      int: 0
    saucer_1_select_ready:
      action: set
      int: 0
    saucer_2_select_ready:
      action: set
      int: 0
    saucer_3_select_ready:
      action: set
      int: 0
    villains_completed_this_ball_total:
      action: set
      int: 0

  villain_mode_running_clear:
    villain_mode_running:
      action: set
      int: 0

  saucer_1_select_ready_set:
    saucer_1_select_ready:
      action: set
      int: 1

  saucer_2_select_ready_set:
    saucer_2_select_ready:
      action: set
      int: 1

  saucer_3_select_ready_set:
    saucer_3_select_ready:
      action: set
      int: 1

  kingpin_ready_set:
    kingpin_ready:
      action: set
      int: 1

  slings_hit:
    score: 110



shots:
  sling_left:
    switch: s_sling_l

  sling_right:
    switch: s_sling_r

shot_groups:
  slings:
    shots: sling_left, sling_right

event_player:
  reset_villain_locate:
    - advance_current_villain

  slings_hit:
    - advance_current_villain

  s_saucer_1_active: saucer_1_villain_start_request
  s_saucer_2_active: saucer_2_villain_start_request
  s_saucer_3_active: saucer_3_villain_start_request

  saucer_1_villain_start_request{current_player.saucer_1_select_ready == 1}: start_mode_villain_select
  saucer_1_villain_start_request{current_player.villain_start_ready == 1 and current_player.saucer_1_select_ready == 0}: start_current_villain

  saucer_2_villain_start_request{current_player.saucer_2_select_ready == 1}: start_mode_villain_select
  saucer_2_villain_start_request{current_player.villain_start_ready == 1 and current_player.saucer_2_select_ready == 0}: start_current_villain

  saucer_3_villain_start_request{current_player.saucer_3_select_ready == 1}: start_mode_villain_select
  saucer_3_villain_start_request{current_player.villain_start_ready == 1 and current_player.saucer_3_select_ready == 0}: start_current_villain

  check_kingpin_ready{current_player.villains_completed_total >= 10}:
    - kingpin_ready_set
    - kingpin_wizard_ready