#config_version=6

mode:
  start_events: mystery_award_collect_bonus
  code: custom_bonus.CustomBonus
  priority: 50


#todo, light shows and video/audio stuff
event_player:
  custom_bonus_complete:
    - upkick
    