#config_version=6

mode:
  start_events: mystery_award_collect_bonus
  stop_events:
    - custom_bonus_complete
    - ball_will_end
  code: custom_bonus.CustomBonus
  priority: 550


widget_player:
  custom_bonus_widget_show:
    custom_bonus:
      action: play
      key: custom_bonus

  custom_bonus_widget_hide:
    custom_bonus:
      action: remove
      key: custom_bonus
    
