#config_version=6

mode:
  start_events: mystery_award_collect_bonus
  stop_events:
    - custom_bonus_complete
    - ball_will_end
  code: custom_bonus.CustomBonus
  priority: 550


slide_player:
  custom_bonus_slide_show:
    bonus:
      action: play

  custom_bonus_slide_hide:
    bonus:
      action: remove
    